# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fogale.ui'
#
# Created: Tue Apr 16 15:50:32 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

#import pyqtgraph as pg
from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import *
import PyQt4.Qwt5 as Qwt
from Variaveis_v2 import var
import numpy as np

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s



try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

"""class CustomViewBox(pg.ViewBox):
    def __init__(self, *args, **kwds):
        pg.ViewBox.__init__(self, *args, **kwds)
        self.setMouseMode(self.RectMode)

    ## reimplement right-click to zoom out
    def mouseClickEvent(self, ev):
        if ev.button() == QtCore.Qt.RightButton:
            self.autoRange()

    def mouseDragEvent(self, ev):
        if ev.button() == QtCore.Qt.RightButton:
            ev.ignore()
        else:
            pg.ViewBox.mouseDragEvent(self, ev)"""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 682)#N:1300, 682, V:853, 682
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 1290, 677)) #831, 626
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Monitor = QtGui.QWidget()
        self.Monitor.setObjectName(_fromUtf8("Monitor"))
        self.groupBox_3 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 10, 1240, 326)) #816, 326
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget = SimplePlot(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(10, 20, 1210, 286))#796
        self.widget.setObjectName(_fromUtf8("widget"))
        self.groupBox_4 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 345, 1042, 251))#686
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 21, 1012, 226))#666
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(30)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        self.groupBox_5 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_5.setGeometry(QtCore.QRect(1061, 345, 120, 251))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.led1_r = QtGui.QLabel(self.groupBox_5)
        self.led1_r.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_r.setText(_fromUtf8(""))
        self.led1_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led1_r.setScaledContents(True)
        self.led1_r.setObjectName(_fromUtf8("led1_r"))
        self.led2_r = QtGui.QLabel(self.groupBox_5)
        self.led2_r.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_r.setText(_fromUtf8(""))
        self.led2_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led2_r.setScaledContents(True)
        self.led2_r.setObjectName(_fromUtf8("led2_r"))
        self.led3_r = QtGui.QLabel(self.groupBox_5)
        self.led3_r.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_r.setText(_fromUtf8(""))
        self.led3_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led3_r.setScaledContents(True)
        self.led3_r.setObjectName(_fromUtf8("led3_r"))
        self.led4_r = QtGui.QLabel(self.groupBox_5)
        self.led4_r.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_r.setText(_fromUtf8(""))
        self.led4_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led4_r.setScaledContents(True)
        self.led4_r.setObjectName(_fromUtf8("led4_r"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(45, 25, 66, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(45, 55, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(45, 85, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(45, 115, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ResButton = QtGui.QPushButton(self.groupBox_5)
        self.ResButton.setGeometry(QtCore.QRect(25, 165, 75, 23))
        self.ResButton.setObjectName(_fromUtf8("ResButton"))
        self.RefButton = QtGui.QPushButton(self.groupBox_5)
        self.RefButton.setGeometry(QtCore.QRect(25, 205, 75, 23))
        self.RefButton.setObjectName(_fromUtf8("RefButton"))
        self.led1_y = QtGui.QLabel(self.groupBox_5)
        self.led1_y.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_y.setText(_fromUtf8(""))
        self.led1_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led1_y.setScaledContents(True)
        self.led1_y.setObjectName(_fromUtf8("led1_y"))
        self.led2_y = QtGui.QLabel(self.groupBox_5)
        self.led2_y.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_y.setText(_fromUtf8(""))
        self.led2_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led2_y.setScaledContents(True)
        self.led2_y.setObjectName(_fromUtf8("led2_y"))
        self.led3_y = QtGui.QLabel(self.groupBox_5)
        self.led3_y.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_y.setText(_fromUtf8(""))
        self.led3_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led3_y.setScaledContents(True)
        self.led3_y.setObjectName(_fromUtf8("led3_y"))
        self.led4_y = QtGui.QLabel(self.groupBox_5)
        self.led4_y.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_y.setText(_fromUtf8(""))
        self.led4_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led4_y.setScaledContents(True)
        self.led4_y.setObjectName(_fromUtf8("led4_y"))
        self.led1_g = QtGui.QLabel(self.groupBox_5)
        self.led1_g.setEnabled(True)
        self.led1_g.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_g.setText(_fromUtf8(""))
        self.led1_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led1_g.setScaledContents(True)
        self.led1_g.setObjectName(_fromUtf8("led1_g"))
        self.led2_g = QtGui.QLabel(self.groupBox_5)
        self.led2_g.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_g.setText(_fromUtf8(""))
        self.led2_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led2_g.setScaledContents(True)
        self.led2_g.setObjectName(_fromUtf8("led2_g"))
        self.led3_g = QtGui.QLabel(self.groupBox_5)
        self.led3_g.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_g.setText(_fromUtf8(""))
        self.led3_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led3_g.setScaledContents(True)
        self.led3_g.setObjectName(_fromUtf8("led3_g"))
        self.led4_g = QtGui.QLabel(self.groupBox_5)
        self.led4_g.setEnabled(True)
        self.led4_g.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_g.setText(_fromUtf8(""))
        self.led4_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led4_g.setScaledContents(True)
        self.led4_g.setObjectName(_fromUtf8("led4_g"))
        self.tabWidget.addTab(self.Monitor, _fromUtf8(""))
        self.Preferences = QtGui.QWidget()
        self.Preferences.setObjectName(_fromUtf8("Preferences"))
        self.groupBox_2 = QtGui.QGroupBox(self.Preferences)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 145, 1225, 446)) #806
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.SaveButton = QtGui.QPushButton(self.groupBox_2)
        self.SaveButton.setGeometry(QtCore.QRect(614, 410, 75, 23)) #405
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.LoadButton = QtGui.QPushButton(self.groupBox_2)
        self.LoadButton.setGeometry(QtCore.QRect(519, 410, 75, 23)) #320
        self.LoadButton.setObjectName(_fromUtf8("LoadButton"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(310, 15, 86, 111)) #275
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.check3 = QtGui.QCheckBox(self.groupBox_6)
        self.check3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.check3.setWhatsThis(_fromUtf8(""))
        self.check3.setChecked(True)
        self.check3.setObjectName(_fromUtf8("check3"))
        self.check4 = QtGui.QCheckBox(self.groupBox_6)
        self.check4.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.check4.setChecked(True)
        self.check4.setObjectName(_fromUtf8("check4"))
        self.check1 = QtGui.QCheckBox(self.groupBox_6)
        self.check1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.check1.setChecked(True)
        self.check1.setObjectName(_fromUtf8("check1"))
        self.check2 = QtGui.QCheckBox(self.groupBox_6)
        self.check2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.check2.setChecked(True)
        self.check2.setObjectName(_fromUtf8("check2"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 265, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 140, 1194, 106))#786
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(30)
        self.tableWidget_2.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(29, item)
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 285, 1194, 106)) #786
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(32)
        self.tableWidget_3.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(31, item)
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(410, 15, 211, 111)) #550
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.PortBox = QtGui.QComboBox(self.groupBox)
        self.PortBox.setGeometry(QtCore.QRect(20, 45, 69, 22))
        self.PortBox.setObjectName(_fromUtf8("PortBox"))
        self.OpenButton = QtGui.QPushButton(self.groupBox)
        self.OpenButton.setGeometry(QtCore.QRect(120, 15, 75, 23)) #120
        self.OpenButton.setObjectName(_fromUtf8("OpenButton"))
        self.CloseButton = QtGui.QPushButton(self.groupBox)
        self.CloseButton.setGeometry(QtCore.QRect(120, 45, 75, 23)) #120
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 25, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.RefreshButton = QtGui.QPushButton(self.groupBox)
        self.RefreshButton.setGeometry(QtCore.QRect(120, 75, 75, 23)) #120
        self.RefreshButton.setObjectName(_fromUtf8("RefreshButton"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 25, 286, 86))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(10, 25, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.t_aq = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.t_aq.setGeometry(QtCore.QRect(10, 45, 62, 22))
        self.t_aq.setSingleStep(0.01)
        self.t_aq.setProperty("value", 10.0)
        self.t_aq.setObjectName(_fromUtf8("t_aq"))
        self.cmp = QtGui.QSpinBox(self.groupBox_8)
        self.cmp.setGeometry(QtCore.QRect(155, 45, 56, 22))
        self.cmp.setMinimum(2)
        self.cmp.setMaximum(10000)
        self.cmp.setProperty("value", 100)
        self.cmp.setObjectName(_fromUtf8("cmp"))
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(155, 25, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.Preferences)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 15, 1225, 121)) #806
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.PlotBox1 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox1.setGeometry(QtCore.QRect(46, 60, 69, 22))
        self.PlotBox1.setObjectName(_fromUtf8("PlotBox1"))
        self.checkPlot1 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot1.setGeometry(QtCore.QRect(46, 40, 70, 17))
        self.checkPlot1.setChecked(False)
        self.checkPlot1.setObjectName(_fromUtf8("checkPlot1"))
        self.PlotBox2 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox2.setGeometry(QtCore.QRect(190, 60, 69, 22))
        self.PlotBox2.setObjectName(_fromUtf8("PlotBox2"))
        self.checkPlot2 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot2.setGeometry(QtCore.QRect(190, 40, 70, 17))
        self.checkPlot2.setObjectName(_fromUtf8("checkPlot2"))
        self.PlotBox3 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox3.setGeometry(QtCore.QRect(335, 60, 69, 22))
        self.PlotBox3.setObjectName(_fromUtf8("PlotBox3"))
        self.checkPlot3 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot3.setGeometry(QtCore.QRect(335, 40, 70, 17))
        self.checkPlot3.setObjectName(_fromUtf8("checkPlot3"))
        self.PlotBox4 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox4.setGeometry(QtCore.QRect(479, 60, 69, 22))
        self.PlotBox4.setObjectName(_fromUtf8("PlotBox4"))
        self.checkPlot4 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot4.setGeometry(QtCore.QRect(479, 40, 70, 17))
        self.checkPlot4.setObjectName(_fromUtf8("checkPlot4"))
        self.PlotBox5 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox5.setGeometry(QtCore.QRect(623, 60, 69, 22))
        self.PlotBox5.setObjectName(_fromUtf8("PlotBox5"))
        self.checkPlot5 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot5.setGeometry(QtCore.QRect(623, 40, 70, 17))
        self.checkPlot5.setObjectName(_fromUtf8("checkPlot5"))
        self.PlotBox6 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox6.setGeometry(QtCore.QRect(768, 60, 69, 22))
        self.PlotBox6.setObjectName(_fromUtf8("PlotBox6"))
        self.checkPlot6 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot6.setGeometry(QtCore.QRect(768, 40, 70, 17))
        self.checkPlot6.setObjectName(_fromUtf8("checkPlot6"))
        self.PlotBox7 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox7.setGeometry(QtCore.QRect(912, 60, 69, 22))
        self.PlotBox7.setObjectName(_fromUtf8("PlotBox7"))
        self.checkPlot7 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot7.setGeometry(QtCore.QRect(912, 40, 70, 17))
        self.checkPlot7.setObjectName(_fromUtf8("checkPlot7"))
        self.PlotBox8 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox8.setGeometry(QtCore.QRect(1056, 60, 69, 22))
        self.PlotBox8.setObjectName(_fromUtf8("PlotBox8"))
        self.checkPlot8 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot8.setGeometry(QtCore.QRect(1056, 40, 70, 17))
        self.checkPlot8.setObjectName(_fromUtf8("checkPlot8"))
        self.tabWidget.addTab(self.Preferences, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        """INICIO DA IMPLEMENTACAO DA INTERFACE GRAFICA PARA PLOTS"""

        """Aba 'Offline'"""
        self.Offline = QtGui.QWidget()
        self.Offline.setObjectName(_fromUtf8("Offline"))
        self.tabWidget.addTab(self.Offline, _fromUtf8(""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Offline), _translate("MainWindow", "Offline", None))

        #calendario
        self.cal = QtGui.QCalendarWidget(self.Offline)
        self.cal.setGridVisible(True)
        self.cal.setGeometry(20,75,600,400)


        #calendar buttons
        self.btn1 = QtGui.QPushButton('Data Inicial',self.Offline)
        #btn1.setCheckable(True)
        self.btn1.setGeometry(245, 500, 75, 23)
        self.btn1.setIconSize(QtCore.QSize(44,44))

        self.btn2 = QtGui.QPushButton('Data Final',self.Offline)
        #btn2.setCheckable(True)
        self.btn2.setGeometry(330, 500, 75, 23)
        self.btn1.setIconSize(QtCore.QSize(44,44))

        self.groupBox_off1 = QtGui.QGroupBox(self.Offline)
        self.groupBox_off1.setGeometry(QtCore.QRect(730, 85, 420, 250)) #816, 326
        self.groupBox_off1.setObjectName(_fromUtf8("groupBox_off1"))

        self.groupBox_off2 = QtGui.QGroupBox(self.groupBox_off1)
        self.groupBox_off2.setGeometry(QtCore.QRect(15, 20, 117, 145)) #816, 326
        self.groupBox_off2.setObjectName(_fromUtf8("groupBox_off1"))

        """Botao de plot 'valores absolutos' para aba Offline"""
        self.plotAbsBtn_off = QtGui.QPushButton(self.groupBox_off2)
        self.plotAbsBtn_off.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.plotAbsBtn_off.setObjectName(_fromUtf8("PlotButton6off"))
        self.plotAbsBtn_off.setText(_translate("MainWindow", "Absoluto", None))
        """Botao de plot dos valores dos sensores em relação a um sensor"""
        self.plotRefSensorBtn_off = QtGui.QPushButton(self.groupBox_off2)
        self.plotRefSensorBtn_off.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.plotRefSensorBtn_off.setObjectName(_fromUtf8("PlotButton3off"))
        self.plotRefSensorBtn_off.setText(_translate("MainWindow", "Sensor", None))

        """Botao de plot dos valores dos sensores em relação a uma média geral"""
        self.plotRefMedGBtn_off = QtGui.QPushButton(self.groupBox_off2)
        self.plotRefMedGBtn_off.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.plotRefMedGBtn_off.setObjectName(_fromUtf8("PlotButton4off"))
        self.plotRefMedGBtn_off.setText(_translate("MainWindow", "Média Geral", None))

        """Botao de plot dos valores dos sensores em relação a um conjunto de valores setados"""
        self.plotRefFixaBtn_off = QtGui.QPushButton(self.groupBox_off2)
        self.plotRefFixaBtn_off.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.plotRefFixaBtn_off.setObjectName(_fromUtf8("PlotButton5off"))
        self.plotRefFixaBtn_off.setText(_translate("MainWindow", "Ref Fixa", None))

        self.groupBox_off3 = QtGui.QGroupBox(self.groupBox_off1)
        self.groupBox_off3.setGeometry(QtCore.QRect(150, 20, 140, 220)) #816, 326
        self.groupBox_off3.setObjectName(_fromUtf8("groupBox_off1"))


        """PlotBox para selecao de plot 'nivel' ou 'temp'"""
        self.plotBox_off = QtGui.QComboBox(self.groupBox_off3)
        self.plotBox_off.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.plotBox_off.setObjectName(_fromUtf8("plotBox"))
        #NOVO{
        self.list = ["Nível", "Temperatura"]
        """adiciona lista de sensores ao menu dos Plots"""
        self.plotBox_off.addItems(self.list)

        self.text1 = QtGui.QLabel("Variável:", self.groupBox_off3)
        self.text1.setGeometry(10, 20, 50, 15)

        """plotBlox para seleção do sensor de referencia na aba 'Offline'"""
        self.plotBoxSens_off = QtGui.QComboBox(self.groupBox_off3)
        self.plotBoxSens_off.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.plotBoxSens_off.setObjectName(_fromUtf8("PlotBoxSensor_off"))

        self.text2 = QtGui.QLabel("Sensor de referência:", self.groupBox_off3)
        self.text2.setGeometry(10, 70, 120, 15)

        """Log para receber data que se quer ter a referencia setada"""
        self.logDateTime_off = QTextEdit(self.groupBox_off3)
        self.logDateTime_off.setReadOnly(False)
        self.logDateTime_off.setLineWrapMode(QTextEdit.NoWrap)
        self.logDateTime_off.moveCursor(QTextCursor.End)
        self.logDateTime_off.setGeometry(10,140,120,23)

        self.text3 = QtGui.QLabel("Hora/data da ref fixa:", self.groupBox_off3)
        self.text3.setGeometry(10, 120, 120, 15)

        """log para estipular quantidade de segundos que se quer ter de shift entre um dado plotado e outro"""
        """self.logShift_off = QTextEdit(self.groupBox_off3)
        self.logShift_off.setReadOnly(False)
        self.logShift_off.setLineWrapMode(QTextEdit.NoWrap)
        self.logShift_off.moveCursor(QTextCursor.End)
        self.logShift_off.setGeometry(10,190,120,23)"""

        """self.plotBoxShift_off = QtGui.QComboBox(self.groupBox_off3)
        self.plotBoxShift_off.setGeometry(QtCore.QRect(10, 190, 120, 23))
        self.plotBoxShift_off.setObjectName(_fromUtf8("PlotBoxShift_off"))"""

        self.plotBoxShift_off = QtGui.QSpinBox(self.groupBox_off3)
        self.plotBoxShift_off.setGeometry(QtCore.QRect(10, 190, 56, 23))
        self.plotBoxShift_off.setMinimum(2)
        self.plotBoxShift_off.setMaximum(10000)
        self.plotBoxShift_off.setProperty("value", 1)
        self.plotBoxShift_off.setObjectName(_fromUtf8("shiftSpin"))

        self.text4 = QtGui.QLabel("Shift de amostragem [seg]:", self.groupBox_off3)
        self.text4.setGeometry(10, 170, 220, 15)


        self.groupBox_off4 = QtGui.QGroupBox(self.groupBox_off1)
        self.groupBox_off4.setGeometry(QtCore.QRect(305, 20, 100,125)) #816, 326
        self.groupBox_off4.setObjectName(_fromUtf8("groupBox_off4"))

        "Check para setar shift de segundos para amostragem"
        self.checkShift_off = QtGui.QCheckBox(self.groupBox_off4)
        self.checkShift_off.setGeometry(QtCore.QRect(10, 100, 120, 17))
        self.checkShift_off.setChecked(False)
        self.checkShift_off.setObjectName(_fromUtf8("checkShift"))

        # Create play button
        self.btn_play = QtGui.QPushButton('Plot',self.groupBox_off4)
        self.btn_play.setGeometry(10,20,73,23)
        #self.btn_play.setIcon(QtGui.QIcon('play.jpg'))
        self.btn_play.setIconSize(QtCore.QSize(45,45))


        # Create play button
        self.setRefBtn_off = QtGui.QPushButton('Set Ref Fix',self.groupBox_off4)
        self.setRefBtn_off.setGeometry(10,70,73,23)
        #self.btn_play.setIcon(QtGui.QIcon('play.jpg'))
        self.setRefBtn_off.setIconSize(QtCore.QSize(45,45))



        """# Create stop button
        self.btn_stop = QtGui.QPushButton('',self.Offline)
        self.btn_stop.setGeometry(x-35,y,30,30)
        self.btn_stop.setIcon(QtGui.QIcon('stop.jpg'))
        self.btn_stop.setIconSize(QtCore.QSize(44,44))"""

        # Create textbox
        self.logOutput_off = QTextEdit(self.Offline)
        self.logOutput_off.setReadOnly(True)
        self.logOutput_off.setLineWrapMode(QTextEdit.NoWrap)
        self.logOutput_off.moveCursor(QTextCursor.End)
        self.logOutput_off.setGeometry(700,350,500,200)

        font = self.logOutput_off.font()
        font.setFamily("Courier")
        font.setPointSize(10)

        self.logOutput_off.setCurrentFont(font)
        #logOutput.setTextColor(color)
        self.logOutput_off.insertPlainText("Analise de dados - HLS Fogale" + '\n')
        self.logOutput_off.insertPlainText("Selecione no calendario o intervalo desejado para analise" + '\n')

        #Input dialog
        #self.Dlg = QInputDialog.getItem(None,"Define Metodo","Selecione forma de analise", ["Variacao Media individual", "Variacao por referencia", "Valor Absoluto", "Variacao Diaria"])

        """Aba 'Online'"""
        self.Online = QtGui.QWidget()
        self.Online.setObjectName(_fromUtf8("Online"))
        self.tabWidget.addTab(self.Online, _fromUtf8(""))
        #self.groupBox_3 = QtGui.QGroupBox(self.Monitor)
        #self.groupBox_3.setGeometry(QtCore.QRect(5, 10, 816, 326))
        #self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget_on = SimplePlot_on(self.Online)
        self.widget_on.setGeometry(QtCore.QRect(10, 10, 1250, 410)) #796, 360
        self.widget_on.setObjectName(_fromUtf8("widget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Online), _translate("MainWindow", "Online", None))


        """self.vb = CustomViewBox()
        self.Online2 = QtGui.QWidget()
        self.Online2.setObjectName(_fromUtf8("Online2"))
        self.tabWidget.addTab(self.Online2, _fromUtf8(""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Online2), _translate("MainWindow", "Online2", None))
        self.pw = pg.PlotWidget(self.Online2, enableMenu=True, title="PlotItem with custom axis and ViewBox<br>Menu disabled, mouse behavior changed: left-drag to zoom, right-click to reset zoom")
        self.pw.setGeometry(QtCore.QRect(5, 10, 600, 200))
        dates = np.arange(8) * (3600*24*356)
        #self.pw.plot(x=dates, y=[1,6,2,4,3,5,6,8], symbol='o')"""
        #nova implementação
        #self.groupBox_2 = QtGui.QGroupBox(self.Monitor)
        #self.groupBox_2.setGeometry(QtCore.QRect(10, 145, 806, 446))
        #self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        #self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        #self.groupBox.setGeometry(QtCore.QRect(550, 15, 211, 111))
        #self.groupBox.setObjectName(_fromUtf8("groupBox"))
        #self.PortBox = QtGui.QComboBox(self.groupBox)
        #self.PortBox.setGeometry(QtCore.QRect(20, 45, 69, 22))
        #self.PortBox.setObjectName(_fromUtf8("PortBox"))
        """Botao de plot, ja obsoleto"""
        """self.PlotButton = QtGui.QPushButton(self.Online)
        self.PlotButton.setGeometry(QtCore.QRect(440, 430, 75, 23))
        self.PlotButton.setObjectName(_fromUtf8("PlotButton"))
        self.PlotButton.setText(_translate("MainWindow", "Plot", None))"""
        """Botao setScale do plot"""
        self.setScaleBtn = QtGui.QPushButton(self.Online)
        self.setScaleBtn.setGeometry(QtCore.QRect(530,490,75,23))
        self.setScaleBtn.setObjectName(_fromUtf8("setScaleButton"))
        self.setScaleBtn.setText(_translate("MainWindow", "Set scale", None))
        """Botao setAutoScale do plot"""
        self.setAutoScaleBtn = QtGui.QPushButton(self.Online)
        self.setAutoScaleBtn.setGeometry(QtCore.QRect(530,520,75,23))
        self.setAutoScaleBtn.setObjectName(_fromUtf8("setAutoScaleButton"))
        self.setAutoScaleBtn.setText(_translate("MainWindow", "Autoscale", None))

        """PlotBox para selecao de plot 'nivel' ou 'temp'"""
        self.plotBox_on = QtGui.QComboBox(self.Online)
        self.plotBox_on.setGeometry(QtCore.QRect(450, 520, 75, 23))
        self.plotBox_on.setObjectName(_fromUtf8("plotBox"))
        #NOVO{
        self.list = ["Nível", "Temperatura"]
        """adiciona lista de sensores ao menu dos Plots"""
        self.plotBox_on.addItems(self.list)


        """Botao de plot do valor absoluto de todos os sensores"""
        self.plotRefFixBtn = QtGui.QPushButton(self.Online)
        self.plotRefFixBtn.setGeometry(QtCore.QRect(30, 480, 75, 23))
        self.plotRefFixBtn.setObjectName(_fromUtf8("PlotButton6"))
        self.plotRefFixBtn.setText(_translate("MainWindow", "Valores Fixos", None))
        """Botao de plot dos valores dos sensores em relação a um sensor"""
        self.plotRefSensorBtn = QtGui.QPushButton(self.Online)
        self.plotRefSensorBtn.setGeometry(QtCore.QRect(30, 510, 75, 23))
        self.plotRefSensorBtn.setObjectName(_fromUtf8("PlotButton3"))
        self.plotRefSensorBtn.setText(_translate("MainWindow", "Sensor", None))
        """Botao de plot dos valores dos sensores em relação a uma média geral"""
        self.plotRefMedGBtn = QtGui.QPushButton(self.Online)
        self.plotRefMedGBtn.setGeometry(QtCore.QRect(30, 540, 75, 23))
        self.plotRefMedGBtn.setObjectName(_fromUtf8("PlotButton4"))
        self.plotRefMedGBtn.setText(_translate("MainWindow", "Média Geral", None))
        """Botao de plot dos valores dos sensores em relação a uma média individual"""
        self.plotRefMedIBtn = QtGui.QPushButton(self.Online)
        self.plotRefMedIBtn.setGeometry(QtCore.QRect(30, 570, 75, 23))
        self.plotRefMedIBtn.setObjectName(_fromUtf8("PlotButton5"))
        self.plotRefMedIBtn.setText(_translate("MainWindow", "Média Local", None))
        """Botao de plot do valor absoluto de todos os sensores"""
        self.plotAbsBtn = QtGui.QPushButton(self.Online)
        self.plotAbsBtn.setGeometry(QtCore.QRect(30, 600, 75, 23))
        self.plotAbsBtn.setObjectName(_fromUtf8("PlotButton7"))
        self.plotAbsBtn.setText(_translate("MainWindow", "Absoluta", None))

        """Botao de stop plot"""
        # Create stop2 button
        self.btn_stop2 = QtGui.QPushButton('',self.Online)
        self.btn_stop2.setGeometry(450, 490, 75, 23)
        self.btn_stop2.setText("Stop Plot")
        self.btn_stop2.setIconSize(QtCore.QSize(44,44))

        self.TextRef = QtGui.QLabel("Opções de referência", self.Online)
        self.TextRef.setGeometry(30, 450, 120, 18)

        self.setRef_onBtn = QtGui.QPushButton(self.Online)
        self.setRef_onBtn.setGeometry(QtCore.QRect(115, 480, 75, 23))
        self.setRef_onBtn.setObjectName(_fromUtf8("PlotButton8"))
        self.setRef_onBtn.setText(_translate("MainWindow", "Set Ref", None))

        """plotBlox para seleção do sensor de referencia"""
        self.plotBoxSens_on = QtGui.QComboBox(self.Online)
        self.plotBoxSens_on.setGeometry(QtCore.QRect(115, 512, 75, 18))
        self.plotBoxSens_on.setObjectName(_fromUtf8("PlotBoxSensor"))

        self.cmp_on = QtGui.QSpinBox(self.Online)
        self.cmp_on.setGeometry(QtCore.QRect(250, 500, 56, 22))
        self.cmp_on.setMinimum(2)
        self.cmp_on.setMaximum(10000)
        self.cmp_on.setProperty("value", 100)
        self.cmp_on.setObjectName(_fromUtf8("cmp"))

        self.checkCmp_on = QtGui.QCheckBox(self.Online)
        self.checkCmp_on.setGeometry(QtCore.QRect(250, 530, 130, 17))
        self.checkCmp_on.setChecked(False)
        self.checkCmp_on.setObjectName(_fromUtf8("checkCmp_on"))

        self.cmpLabel = QtGui.QLabel(self.Online)
        self.cmpLabel.setGeometry(QtCore.QRect(250, 477, 126, 16))
        self.cmpLabel.setObjectName(_fromUtf8("label_6"))
        self.cmpLabel.setText(_translate("MainWindow", "Number of Graph Points:", None))

        #self.groupBox_7 = QtGui.QGroupBox(self.Monitor)
        #self.groupBox_7.setGeometry(QtCore.QRect(10, 15, 806, 121))
        #self.groupBox_7.setObjectName(_fromUtf8("groupBox_7")


        x=200
        y=570
        """checkPlots"""
        #self.PlotBox1 = QtGui.QComboBox(self.Online)
        #self.PlotBox1.setGeometry(QtCore.QRect(410, 500, 69, 22))
        #self.PlotBox1.setObjectName(_fromUtf8("PlotBox1"))
        self.checkPlot1_on = QtGui.QCheckBox(self.Online)
        self.checkPlot1_on.setGeometry(QtCore.QRect(x, y, 70, 17))
        self.checkPlot1_on.setChecked(False)
        self.checkPlot1_on.setObjectName(_fromUtf8("checkPlot1_on"))
        #self.checkPlot1_on.setText(_translate("MainWindow", var.disp_sensores[0][0] , None))
        #self.PlotBox2 = QtGui.QComboBox(self.Online)
        #self.PlotBox2.setGeometry(QtCore.QRect(505, 500, 69, 22))
        #self.PlotBox2.setObjectName(_fromUtf8("PlotBox2"))
        self.checkPlot2_on = QtGui.QCheckBox(self.Online)
        self.checkPlot2_on.setGeometry(QtCore.QRect(x+80, y, 70, 17))
        self.checkPlot2_on.setObjectName(_fromUtf8("checkPlot2"))
        #self.PlotBox3 = QtGui.QComboBox(self.Online)
        #self.PlotBox3.setGeometry(QtCore.QRect(600, 500, 69, 22))
        #self.PlotBox3.setObjectName(_fromUtf8("PlotBox3"))
        self.checkPlot3_on = QtGui.QCheckBox(self.Online)
        self.checkPlot3_on.setGeometry(QtCore.QRect(x+160, y, 70, 17))
        self.checkPlot3_on.setObjectName(_fromUtf8("checkPlot3"))
        #self.PlotBox4 = QtGui.QComboBox(self.Online)
        #self.PlotBox4.setGeometry(QtCore.QRect(695, 500, 69, 22))
        #self.PlotBox4.setObjectName(_fromUtf8("PlotBox4"))
        self.checkPlot4_on = QtGui.QCheckBox(self.Online)
        self.checkPlot4_on.setGeometry(QtCore.QRect(x+240, y, 70, 17))
        self.checkPlot4_on.setObjectName(_fromUtf8("checkPlot4"))
        #self.PlotBox5 = QtGui.QComboBox(self.Online)
        #self.PlotBox5.setGeometry(QtCore.QRect(410, 550, 69, 22))
        #self.PlotBox5.setObjectName(_fromUtf8("PlotBox5"))
        self.checkPlot5_on = QtGui.QCheckBox(self.Online)
        self.checkPlot5_on.setGeometry(QtCore.QRect(x+320, y, 70, 17))
        self.checkPlot5_on.setObjectName(_fromUtf8("checkPlot5"))
        #self.PlotBox6 = QtGui.QComboBox(self.Online)
        #self.PlotBox6.setGeometry(QtCore.QRect(505, 550, 69, 22))
        #self.PlotBox6.setObjectName(_fromUtf8("PlotBox6"))
        self.checkPlot6_on = QtGui.QCheckBox(self.Online)
        self.checkPlot6_on.setGeometry(QtCore.QRect(x+400, y, 70, 17))
        self.checkPlot6_on.setObjectName(_fromUtf8("checkPlot6"))
        #self.PlotBox7 = QtGui.QComboBox(self.Online)
        #self.PlotBox7.setGeometry(QtCore.QRect(600, 550, 69, 22))
        #self.PlotBox7.setObjectName(_fromUtf8("PlotBox7"))
        self.checkPlot7_on = QtGui.QCheckBox(self.Online)
        self.checkPlot7_on.setGeometry(QtCore.QRect(x+480, y, 70, 17))
        self.checkPlot7_on.setObjectName(_fromUtf8("checkPlot7"))
        #self.PlotBox8 = QtGui.QComboBox(self.Online)
        #self.PlotBox8.setGeometry(QtCore.QRect(695, 550, 69, 22))
        #self.PlotBox8.setObjectName(_fromUtf8("PlotBox8"))
        self.checkPlot8_on = QtGui.QCheckBox(self.Online)
        self.checkPlot8_on.setGeometry(QtCore.QRect(x+560, y, 70, 17))
        self.checkPlot8_on.setObjectName(_fromUtf8("checkPlot8"))
        self.checkPlot9_on = QtGui.QCheckBox(self.Online)
        self.checkPlot9_on.setGeometry(QtCore.QRect(x, y+30, 70, 17))
        self.checkPlot9_on.setObjectName(_fromUtf8("checkPlot9"))
        self.checkPlot10_on = QtGui.QCheckBox(self.Online)
        self.checkPlot10_on.setGeometry(QtCore.QRect(x+80, y+30, 70, 17))
        self.checkPlot10_on.setObjectName(_fromUtf8("checkPlot10"))
        self.checkPlot11_on = QtGui.QCheckBox(self.Online)
        self.checkPlot11_on.setGeometry(QtCore.QRect(x+160, y+30, 70, 17))
        self.checkPlot11_on.setObjectName(_fromUtf8("checkPlot11"))
        self.checkPlot12_on = QtGui.QCheckBox(self.Online)
        self.checkPlot12_on.setGeometry(QtCore.QRect(x+240, y+30, 70, 17))
        self.checkPlot12_on.setObjectName(_fromUtf8("checkPlot12"))
        self.checkPlot13_on = QtGui.QCheckBox(self.Online)
        self.checkPlot13_on.setGeometry(QtCore.QRect(x+320, y+30, 70, 17))
        self.checkPlot13_on.setObjectName(_fromUtf8("checkPlot13"))
        self.checkPlot14_on = QtGui.QCheckBox(self.Online)
        self.checkPlot14_on.setGeometry(QtCore.QRect(x+400, y+30, 70, 17))
        self.checkPlot14_on.setObjectName(_fromUtf8("checkPlot14"))
        self.checkPlot15_on = QtGui.QCheckBox(self.Online)
        self.checkPlot15_on.setGeometry(QtCore.QRect(x+480, y+30, 70, 17))
        self.checkPlot15_on.setObjectName(_fromUtf8("checkPlot15"))
        self.checkPlot16_on = QtGui.QCheckBox(self.Online)
        self.checkPlot16_on.setGeometry(QtCore.QRect(x+560, y+30, 70, 17))
        self.checkPlot16_on.setObjectName(_fromUtf8("checkPlot16"))

        # scaleMinY textbox
        self.logMinY = QTextEdit(self.Online)
        self.logMinY.setReadOnly(False)
        self.logMinY.setLineWrapMode(QTextEdit.NoWrap)
        self.logMinY.moveCursor(QTextCursor.End)
        self.logMinY.setGeometry(640,520,70,20)

        # scaleMaxY textbox 600,440,75,23
        self.logMaxY = QTextEdit(self.Online)
        self.logMaxY.setReadOnly(False)
        self.logMaxY.setLineWrapMode(QTextEdit.NoWrap)
        self.logMaxY.moveCursor(QTextCursor.End)
        self.logMaxY.setGeometry(640,490,70,20)

        # scaleMinX textbox 600,470,75,23
        self.logMinX = QTextEdit(self.Online)
        self.logMinX.setReadOnly(False)
        self.logMinX.setLineWrapMode(QTextEdit.NoWrap)
        self.logMinX.moveCursor(QTextCursor.End)
        self.logMinX.setGeometry(720,520,100,20)

        # scaleMaxX textbox 600,440,75,23
        self.logMaxX = QTextEdit(self.Online)
        self.logMaxX.setReadOnly(False)
        self.logMaxX.setLineWrapMode(QTextEdit.NoWrap)
        self.logMaxX.moveCursor(QTextCursor.End)
        self.logMaxX.setGeometry(720,490,100,20)

        # log para se colocar a data que se pretende ver no gráfico
        """self.logDate = QTextEdit(self.Online)
        self.logDate.setReadOnly(False)
        self.logDate.setLineWrapMode(QTextEdit.NoWrap)
        self.logDate.moveCursor(QTextCursor.End)
        self.logDate.setGeometry(830,490,120,20)"""

        """PlotBox para selecao da data para o 'set scale'"""
        self.plotBox_data = QtGui.QComboBox(self.Online)
        self.plotBox_data.setGeometry(QtCore.QRect(830, 490, 100, 23))
        self.plotBox_data.setObjectName(_fromUtf8("plotBox_data"))
        #NOVO{

        self.textMax = QtGui.QLabel("Max", self.Online)
        self.textMax.setGeometry(615, 493, 20, 15)
        self.textMin = QtGui.QLabel("Min", self.Online)
        self.textMin.setGeometry(615, 523, 20, 15)
        self.textX = QtGui.QLabel("Eixo X", self.Online)
        self.textX.setGeometry(720, 473, 30, 15)
        self.textY = QtGui.QLabel("Eixo Y", self.Online)
        self.textY.setGeometry(640, 473, 30, 15)
        self.textData = QtGui.QLabel("Data:", self.Online)
        self.textData.setGeometry(830, 473, 30, 15)


        font = self.logMaxY.font()
        font.setFamily("Courier")
        font.setPointSize(10)

        self.logMinY.setCurrentFont(font)
        self.logMinY.insertPlainText("0")
        self.logMaxY.setCurrentFont(font)
        self.logMaxY.insertPlainText("0")
        self.logMinX.setCurrentFont(font)
        self.logMinX.insertPlainText("0")
        self.logMaxX.setCurrentFont(font)
        self.logMaxX.insertPlainText("0")

        # Create textbox para aba 'Online'
        self.logOutput_on = QTextEdit(self.Online)
        self.logOutput_on.setReadOnly(True)
        self.logOutput_on.setLineWrapMode(QTextEdit.NoWrap)
        self.logOutput_on.moveCursor(QTextCursor.End)
        self.logOutput_on.setGeometry(835,520,430,100)

        font = self.logOutput_on.font()
        font.setFamily("Courier")
        font.setPointSize(10)

        self.logOutput_on.setCurrentFont(font)
        #logOutput.setTextColor(color)
        self.logOutput_on.insertPlainText("Analise de dados - HLS Fogale" + '\n')

        """Textos para checkPlots"""
        x = 217
        y = 570
        font1 = QFont()
        font1.setPointSize(12)
        self.text1 = QtGui.QLabel("Rack1:", self.Online)
        self.text1.setFont(font1)
        self.text1.setGeometry(140, y, 50, 15)
        self.text2 = QtGui.QLabel("Rack2:", self.Online)
        self.text2.setFont(font1)
        self.text2.setGeometry(140, y+30, 50, 15)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Graphics", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "D [mm]", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "D-Do [mm]", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Davg [mm]", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "T [ºC]", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "T-To [ºC]", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tavg [ºC]", None))
        ## ordem na tabela referente a disposição atual dos sensores ###
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        self.groupBox_5.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.groupBox_5.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Rack\'s State", None))
        self.led1_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.label.setText(_translate("MainWindow", "Rack 1", None))
        self.label_2.setText(_translate("MainWindow", "Rack 2", None))
        self.label_3.setText(_translate("MainWindow", "Rack 3", None))
        self.label_4.setText(_translate("MainWindow", "Rack 4", None))
        self.ResButton.setToolTip(_translate("MainWindow", "Reset Racks", None))
        self.ResButton.setStatusTip(_translate("MainWindow", "Reset Racks", None))
        self.ResButton.setText(_translate("MainWindow", "Reset", None))
        self.RefButton.setToolTip(_translate("MainWindow", "Set Current Values as Reference", None))
        self.RefButton.setStatusTip(_translate("MainWindow", "Set Current Values as Reference", None))
        self.RefButton.setText(_translate("MainWindow", "Set Ref", None))
        self.led1_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Monitor), _translate("MainWindow", "Monitor", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "General Preferences", None))
        self.SaveButton.setToolTip(_translate("MainWindow", "Save Preferences", None))
        self.SaveButton.setStatusTip(_translate("MainWindow", "Save Preferences", None))
        self.SaveButton.setText(_translate("MainWindow", "Save", None))
        self.LoadButton.setToolTip(_translate("MainWindow", "Load Preferences From File", None))
        self.LoadButton.setStatusTip(_translate("MainWindow", "Load Preferences From File", None))
        self.LoadButton.setText(_translate("MainWindow", "Load", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Enable Racks", None))
        self.check3.setToolTip(_translate("MainWindow", "Enable/Disable Rack 3", None))
        self.check3.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 3", None))
        self.check3.setText(_translate("MainWindow", "Rack 3", None))
        self.check4.setToolTip(_translate("MainWindow", "Enable/Disable Rack 4", None))
        self.check4.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 4", None))
        self.check4.setText(_translate("MainWindow", "Rack 4", None))
        self.check1.setToolTip(_translate("MainWindow", "Enable/Disable Rack 1", None))
        self.check1.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 1", None))
        self.check1.setText(_translate("MainWindow", "Rack 1", None))
        self.check2.setToolTip(_translate("MainWindow", "Enable/Disable Rack 2", None))
        self.check2.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 2", None))
        self.check2.setText(_translate("MainWindow", "Rack 2", None))
        self.label_8.setText(_translate("MainWindow", "Reference Values:", None))
        self.label_9.setText(_translate("MainWindow", "Average Values:", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Do [mm]", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "To [ºC]", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget_2.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget_2.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget_2.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget_2.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget_2.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget_2.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget_2.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget_2.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget_2.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Davg [mm]", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tavg [ºC]", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget_3.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget_3.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget_3.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget_3.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget_3.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget_3.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        item = self.tableWidget_3.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "H7DC-62", None))
        item = self.tableWidget_3.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "H7DC-63", None))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Communication", None))
        self.PortBox.setToolTip(_translate("MainWindow", "Serial Port", None))
        self.PortBox.setStatusTip(_translate("MainWindow", "Serial Port", None))
        self.OpenButton.setToolTip(_translate("MainWindow", "Open Communication", None))
        self.OpenButton.setStatusTip(_translate("MainWindow", "Open Communication", None))
        self.OpenButton.setText(_translate("MainWindow", "Open", None))
        self.CloseButton.setToolTip(_translate("MainWindow", "Close Communication", None))
        self.CloseButton.setStatusTip(_translate("MainWindow", "Close Communication", None))
        self.CloseButton.setText(_translate("MainWindow", "Close", None))
        self.label_7.setText(_translate("MainWindow", "Com. Port:", None))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Acquisition Preferences", None))
        self.label_5.setText(_translate("MainWindow", "Acquisition Interval [s]:", None))
        self.t_aq.setToolTip(_translate("MainWindow", "Acquisition Interval", None))
        self.t_aq.setStatusTip(_translate("MainWindow", "Acquisition Interval", None))
        self.cmp.setToolTip(_translate("MainWindow", "Number of points in graph", None))
        self.cmp.setStatusTip(_translate("MainWindow", "Number of points in graph", None))
        self.label_6.setText(_translate("MainWindow", "Number of Graph Points:", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot Preferences", None))
        self.PlotBox1.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox1.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot1.setToolTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot1.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot1.setText(_translate("MainWindow", "Plot 1:", None))
        self.PlotBox2.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox2.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot2.setToolTip(_translate("MainWindow", "Enable/Disable Plot 2", None))
        self.checkPlot2.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot2.setText(_translate("MainWindow", "Plot 2:", None))
        self.PlotBox3.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox3.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot3.setToolTip(_translate("MainWindow", "Enable/Disable Plot 3", None))
        self.checkPlot3.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 3", None))
        self.checkPlot3.setText(_translate("MainWindow", "Plot 3:", None))
        self.PlotBox4.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox4.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot4.setToolTip(_translate("MainWindow", "Enable/Disable Plot 4", None))
        self.checkPlot4.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 4", None))
        self.checkPlot4.setText(_translate("MainWindow", "Plot 4:", None))
        self.PlotBox5.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox5.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot5.setToolTip(_translate("MainWindow", "Enable/Disable Plot 5", None))
        self.checkPlot5.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 5", None))
        self.checkPlot5.setText(_translate("MainWindow", "Plot 5:", None))
        self.PlotBox6.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox6.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot6.setToolTip(_translate("MainWindow", "Enable/Disable Plot 6", None))
        self.checkPlot6.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 6", None))
        self.checkPlot6.setText(_translate("MainWindow", "Plot 6:", None))
        self.PlotBox7.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox7.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot7.setToolTip(_translate("MainWindow", "Enable/Disable Plot 7", None))
        self.checkPlot7.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 7", None))
        self.checkPlot7.setText(_translate("MainWindow", "Plot 7:", None))
        self.PlotBox8.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox8.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot8.setToolTip(_translate("MainWindow", "Enable/Disable Plot 8", None))
        self.checkPlot8.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 8", None))
        self.checkPlot8.setText(_translate("MainWindow", "Plot 8:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preferences), _translate("MainWindow", "Preferences", None))

        """NOVO"""
        self.checkPlot1_on.setText(_translate("MainWindow", var.disp_sensores[0][0] , None))
        self.checkPlot2_on.setText(_translate("MainWindow", var.disp_sensores[0][1] , None))
        self.checkPlot3_on.setText(_translate("MainWindow", var.disp_sensores[0][2] , None))
        self.checkPlot4_on.setText(_translate("MainWindow", var.disp_sensores[0][3] , None))
        self.checkPlot5_on.setText(_translate("MainWindow", var.disp_sensores[0][4] , None))
        self.checkPlot6_on.setText(_translate("MainWindow", var.disp_sensores[0][5] , None))
        self.checkPlot7_on.setText(_translate("MainWindow", var.disp_sensores[0][6] , None))
        self.checkPlot8_on.setText(_translate("MainWindow", var.disp_sensores[0][7] , None))
        self.checkPlot9_on.setText(_translate("MainWindow", var.disp_sensores[1][0] , None))
        self.checkPlot10_on.setText(_translate("MainWindow", var.disp_sensores[1][1] , None))
        self.checkPlot11_on.setText(_translate("MainWindow", var.disp_sensores[1][2] , None))
        self.checkPlot12_on.setText(_translate("MainWindow", var.disp_sensores[1][3] , None))
        self.checkPlot13_on.setText(_translate("MainWindow", var.disp_sensores[1][4] , None))
        self.checkPlot14_on.setText(_translate("MainWindow", var.disp_sensores[1][5] , None))
        self.checkPlot15_on.setText(_translate("MainWindow", var.disp_sensores[1][6] , None))
        self.checkPlot16_on.setText(_translate("MainWindow", var.disp_sensores[1][7] , None))
        self.checkCmp_on.setText(_translate("MainWindow", "Limitar número de pontos" , None))
        self.checkShift_off.setText(_translate("MainWindow", "Set Shift ON" , None))

        self.groupBox_off1.setTitle(_translate("MainWindow", "Propriedades do plot", None))
        self.groupBox_off2.setTitle(_translate("MainWindow", "Opções de referência", None))
        self.groupBox_off3.setTitle(_translate("MainWindow", "Preferências", None))
        self.groupBox_off4.setTitle(_translate("MainWindow", "Ações", None))

        self.logDateTime_off.setToolTip(_translate("MainWindow", "Set the date and time of the data that is wanted to be de referency values. Format: HH:MM:SS dd/mm/yyyy", None))
        self.text3.setToolTip(_translate("MainWindow", "Set the date and time of the data that is wanted to be de referency values. Format: HH:MM:SS dd/mm/yyyy", None))


from PlotGUI_Qwt_Multi_v3 import SimplePlot
from PlotGUI_Qwt_Multi_v3 import SimplePlot_on
