# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fogale.ui'
#
# Created: Tue Apr 16 15:50:32 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(853, 682)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 831, 626))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Monitor = QtGui.QWidget()
        self.Monitor.setObjectName(_fromUtf8("Monitor"))
        self.groupBox_3 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 10, 816, 326))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget = SimplePlot(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(10, 20, 796, 286))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.groupBox_4 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 345, 686, 251))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 21, 666, 226))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(30)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        self.groupBox_5 = QtGui.QGroupBox(self.Monitor)
        self.groupBox_5.setGeometry(QtCore.QRect(700, 345, 120, 251))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.led1_r = QtGui.QLabel(self.groupBox_5)
        self.led1_r.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_r.setText(_fromUtf8(""))
        self.led1_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led1_r.setScaledContents(True)
        self.led1_r.setObjectName(_fromUtf8("led1_r"))
        self.led2_r = QtGui.QLabel(self.groupBox_5)
        self.led2_r.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_r.setText(_fromUtf8(""))
        self.led2_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led2_r.setScaledContents(True)
        self.led2_r.setObjectName(_fromUtf8("led2_r"))
        self.led3_r = QtGui.QLabel(self.groupBox_5)
        self.led3_r.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_r.setText(_fromUtf8(""))
        self.led3_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led3_r.setScaledContents(True)
        self.led3_r.setObjectName(_fromUtf8("led3_r"))
        self.led4_r = QtGui.QLabel(self.groupBox_5)
        self.led4_r.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_r.setText(_fromUtf8(""))
        self.led4_r.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_red_button.ico")))
        self.led4_r.setScaledContents(True)
        self.led4_r.setObjectName(_fromUtf8("led4_r"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(45, 25, 66, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(45, 55, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(45, 85, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(45, 115, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ResButton = QtGui.QPushButton(self.groupBox_5)
        self.ResButton.setGeometry(QtCore.QRect(25, 165, 75, 23))
        self.ResButton.setObjectName(_fromUtf8("ResButton"))
        self.RefButton = QtGui.QPushButton(self.groupBox_5)
        self.RefButton.setGeometry(QtCore.QRect(25, 205, 75, 23))
        self.RefButton.setObjectName(_fromUtf8("RefButton"))
        self.led1_y = QtGui.QLabel(self.groupBox_5)
        self.led1_y.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_y.setText(_fromUtf8(""))
        self.led1_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led1_y.setScaledContents(True)
        self.led1_y.setObjectName(_fromUtf8("led1_y"))
        self.led2_y = QtGui.QLabel(self.groupBox_5)
        self.led2_y.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_y.setText(_fromUtf8(""))
        self.led2_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led2_y.setScaledContents(True)
        self.led2_y.setObjectName(_fromUtf8("led2_y"))
        self.led3_y = QtGui.QLabel(self.groupBox_5)
        self.led3_y.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_y.setText(_fromUtf8(""))
        self.led3_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led3_y.setScaledContents(True)
        self.led3_y.setObjectName(_fromUtf8("led3_y"))
        self.led4_y = QtGui.QLabel(self.groupBox_5)
        self.led4_y.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_y.setText(_fromUtf8(""))
        self.led4_y.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_yellow_button.ico")))
        self.led4_y.setScaledContents(True)
        self.led4_y.setObjectName(_fromUtf8("led4_y"))
        self.led1_g = QtGui.QLabel(self.groupBox_5)
        self.led1_g.setEnabled(True)
        self.led1_g.setGeometry(QtCore.QRect(5, 15, 35, 35))
        self.led1_g.setText(_fromUtf8(""))
        self.led1_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led1_g.setScaledContents(True)
        self.led1_g.setObjectName(_fromUtf8("led1_g"))
        self.led2_g = QtGui.QLabel(self.groupBox_5)
        self.led2_g.setGeometry(QtCore.QRect(5, 45, 35, 35))
        self.led2_g.setText(_fromUtf8(""))
        self.led2_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led2_g.setScaledContents(True)
        self.led2_g.setObjectName(_fromUtf8("led2_g"))
        self.led3_g = QtGui.QLabel(self.groupBox_5)
        self.led3_g.setGeometry(QtCore.QRect(5, 75, 35, 35))
        self.led3_g.setText(_fromUtf8(""))
        self.led3_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led3_g.setScaledContents(True)
        self.led3_g.setObjectName(_fromUtf8("led3_g"))
        self.led4_g = QtGui.QLabel(self.groupBox_5)
        self.led4_g.setEnabled(True)
        self.led4_g.setGeometry(QtCore.QRect(5, 105, 35, 35))
        self.led4_g.setText(_fromUtf8(""))
        self.led4_g.setPixmap(QtGui.QPixmap(_fromUtf8("Images/glossy_green_button.ico")))
        self.led4_g.setScaledContents(True)
        self.led4_g.setObjectName(_fromUtf8("led4_g"))
        self.tabWidget.addTab(self.Monitor, _fromUtf8(""))
        self.Preferences = QtGui.QWidget()
        self.Preferences.setObjectName(_fromUtf8("Preferences"))
        self.groupBox_2 = QtGui.QGroupBox(self.Preferences)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 145, 806, 446))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.SaveButton = QtGui.QPushButton(self.groupBox_2)
        self.SaveButton.setGeometry(QtCore.QRect(405, 410, 75, 23))
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.LoadButton = QtGui.QPushButton(self.groupBox_2)
        self.LoadButton.setGeometry(QtCore.QRect(320, 410, 75, 23))
        self.LoadButton.setObjectName(_fromUtf8("LoadButton"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(375, 15, 86, 111))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.check3 = QtGui.QCheckBox(self.groupBox_6)
        self.check3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.check3.setWhatsThis(_fromUtf8(""))
        self.check3.setChecked(True)
        self.check3.setObjectName(_fromUtf8("check3"))
        self.check4 = QtGui.QCheckBox(self.groupBox_6)
        self.check4.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.check4.setChecked(True)
        self.check4.setObjectName(_fromUtf8("check4"))
        self.check1 = QtGui.QCheckBox(self.groupBox_6)
        self.check1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.check1.setChecked(True)
        self.check1.setObjectName(_fromUtf8("check1"))
        self.check2 = QtGui.QCheckBox(self.groupBox_6)
        self.check2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.check2.setChecked(True)
        self.check2.setObjectName(_fromUtf8("check2"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 265, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 140, 786, 106))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(30)
        self.tableWidget_2.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(29, item)
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 285, 786, 106))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(32)
        self.tableWidget_3.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(31, item)
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(550, 15, 211, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.PortBox = QtGui.QComboBox(self.groupBox)
        self.PortBox.setGeometry(QtCore.QRect(20, 45, 69, 22))
        self.PortBox.setObjectName(_fromUtf8("PortBox"))
        self.OpenButton = QtGui.QPushButton(self.groupBox)
        self.OpenButton.setGeometry(QtCore.QRect(120, 15, 75, 23))
        self.OpenButton.setObjectName(_fromUtf8("OpenButton"))
        self.CloseButton = QtGui.QPushButton(self.groupBox)
        self.CloseButton.setGeometry(QtCore.QRect(120, 45, 75, 23))
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 25, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.RefreshButton = QtGui.QPushButton(self.groupBox)
        self.RefreshButton.setGeometry(QtCore.QRect(120, 75, 75, 23))
        self.RefreshButton.setObjectName(_fromUtf8("RefreshButton"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 25, 286, 86))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(10, 25, 126, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.t_aq = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.t_aq.setGeometry(QtCore.QRect(10, 45, 62, 22))
        self.t_aq.setSingleStep(0.01)
        self.t_aq.setProperty("value", 10.0)
        self.t_aq.setObjectName(_fromUtf8("t_aq"))
        self.cmp = QtGui.QSpinBox(self.groupBox_8)
        self.cmp.setGeometry(QtCore.QRect(155, 45, 56, 22))
        self.cmp.setMinimum(2)
        self.cmp.setMaximum(10000)
        self.cmp.setProperty("value", 100)
        self.cmp.setObjectName(_fromUtf8("cmp"))
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(155, 25, 126, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.Preferences)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 15, 806, 121))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.PlotBox1 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox1.setGeometry(QtCore.QRect(30, 60, 69, 22))
        self.PlotBox1.setObjectName(_fromUtf8("PlotBox1"))
        self.checkPlot1 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot1.setGeometry(QtCore.QRect(30, 40, 70, 17))
        self.checkPlot1.setChecked(False)
        self.checkPlot1.setObjectName(_fromUtf8("checkPlot1"))
        self.PlotBox2 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox2.setGeometry(QtCore.QRect(125, 60, 69, 22))
        self.PlotBox2.setObjectName(_fromUtf8("PlotBox2"))
        self.checkPlot2 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot2.setGeometry(QtCore.QRect(125, 40, 70, 17))
        self.checkPlot2.setObjectName(_fromUtf8("checkPlot2"))
        self.PlotBox3 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox3.setGeometry(QtCore.QRect(220, 60, 69, 22))
        self.PlotBox3.setObjectName(_fromUtf8("PlotBox3"))
        self.checkPlot3 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot3.setGeometry(QtCore.QRect(220, 40, 70, 17))
        self.checkPlot3.setObjectName(_fromUtf8("checkPlot3"))
        self.PlotBox4 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox4.setGeometry(QtCore.QRect(315, 60, 69, 22))
        self.PlotBox4.setObjectName(_fromUtf8("PlotBox4"))
        self.checkPlot4 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot4.setGeometry(QtCore.QRect(315, 40, 70, 17))
        self.checkPlot4.setObjectName(_fromUtf8("checkPlot4"))
        self.PlotBox5 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox5.setGeometry(QtCore.QRect(410, 60, 69, 22))
        self.PlotBox5.setObjectName(_fromUtf8("PlotBox5"))
        self.checkPlot5 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot5.setGeometry(QtCore.QRect(410, 40, 70, 17))
        self.checkPlot5.setObjectName(_fromUtf8("checkPlot5"))
        self.PlotBox6 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox6.setGeometry(QtCore.QRect(505, 60, 69, 22))
        self.PlotBox6.setObjectName(_fromUtf8("PlotBox6"))
        self.checkPlot6 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot6.setGeometry(QtCore.QRect(505, 40, 70, 17))
        self.checkPlot6.setObjectName(_fromUtf8("checkPlot6"))
        self.PlotBox7 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox7.setGeometry(QtCore.QRect(600, 60, 69, 22))
        self.PlotBox7.setObjectName(_fromUtf8("PlotBox7"))
        self.checkPlot7 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot7.setGeometry(QtCore.QRect(600, 40, 70, 17))
        self.checkPlot7.setObjectName(_fromUtf8("checkPlot7"))
        self.PlotBox8 = QtGui.QComboBox(self.groupBox_7)
        self.PlotBox8.setGeometry(QtCore.QRect(695, 60, 69, 22))
        self.PlotBox8.setObjectName(_fromUtf8("PlotBox8"))
        self.checkPlot8 = QtGui.QCheckBox(self.groupBox_7)
        self.checkPlot8.setGeometry(QtCore.QRect(695, 40, 70, 17))
        self.checkPlot8.setObjectName(_fromUtf8("checkPlot8"))
        self.tabWidget.addTab(self.Preferences, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Graphics", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "D [mm]", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "D-Do [mm]", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Davg [mm]", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "T [ºC]", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "T-To [ºC]", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tavg [ºC]", None))
        ## ordem na tabela referente a disposição atual dos sensores ###
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        self.groupBox_5.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.groupBox_5.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Rack\'s State", None))
        self.led1_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.label.setText(_translate("MainWindow", "Rack 1", None))
        self.label_2.setText(_translate("MainWindow", "Rack 2", None))
        self.label_3.setText(_translate("MainWindow", "Rack 3", None))
        self.label_4.setText(_translate("MainWindow", "Rack 4", None))
        self.ResButton.setToolTip(_translate("MainWindow", "Reset Racks", None))
        self.ResButton.setStatusTip(_translate("MainWindow", "Reset Racks", None))
        self.ResButton.setText(_translate("MainWindow", "Reset", None))
        self.RefButton.setToolTip(_translate("MainWindow", "Set Current Values as Reference", None))
        self.RefButton.setStatusTip(_translate("MainWindow", "Set Current Values as Reference", None))
        self.RefButton.setText(_translate("MainWindow", "Set Ref", None))
        self.led1_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led1_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led2_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led3_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.led4_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Monitor), _translate("MainWindow", "Monitor", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "General Preferences", None))
        self.SaveButton.setToolTip(_translate("MainWindow", "Save Preferences", None))
        self.SaveButton.setStatusTip(_translate("MainWindow", "Save Preferences", None))
        self.SaveButton.setText(_translate("MainWindow", "Save", None))
        self.LoadButton.setToolTip(_translate("MainWindow", "Load Preferences From File", None))
        self.LoadButton.setStatusTip(_translate("MainWindow", "Load Preferences From File", None))
        self.LoadButton.setText(_translate("MainWindow", "Load", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Enable Racks", None))
        self.check3.setToolTip(_translate("MainWindow", "Enable/Disable Rack 3", None))
        self.check3.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 3", None))
        self.check3.setText(_translate("MainWindow", "Rack 3", None))
        self.check4.setToolTip(_translate("MainWindow", "Enable/Disable Rack 4", None))
        self.check4.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 4", None))
        self.check4.setText(_translate("MainWindow", "Rack 4", None))
        self.check1.setToolTip(_translate("MainWindow", "Enable/Disable Rack 1", None))
        self.check1.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 1", None))
        self.check1.setText(_translate("MainWindow", "Rack 1", None))
        self.check2.setToolTip(_translate("MainWindow", "Enable/Disable Rack 2", None))
        self.check2.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 2", None))
        self.check2.setText(_translate("MainWindow", "Rack 2", None))
        self.label_8.setText(_translate("MainWindow", "Reference Values:", None))
        self.label_9.setText(_translate("MainWindow", "Average Values:", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Do [mm]", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "To [ºC]", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget_2.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget_2.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget_2.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget_2.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget_2.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget_2.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget_2.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget_2.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget_2.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Davg [mm]", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tavg [ºC]", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-40", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-59", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-47", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-46", None))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-39", None))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-52", None))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-33", None))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-57", None))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-36", None))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-44", None))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42", None))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-56", None))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-45", None))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-38", None))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-32", None))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-55", None))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48", None))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49", None))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50", None))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51", None))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-34", None))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53", None))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-35", None))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-54", None))
        item = self.tableWidget_3.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-37", None))
        item = self.tableWidget_3.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-41", None))
        item = self.tableWidget_3.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58", None))
        item = self.tableWidget_3.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-43", None))
        item = self.tableWidget_3.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60", None))
        item = self.tableWidget_3.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61", None))
        item = self.tableWidget_3.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "H7DC-62", None))
        item = self.tableWidget_3.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "H7DC-63", None))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Communication", None))
        self.PortBox.setToolTip(_translate("MainWindow", "Serial Port", None))
        self.PortBox.setStatusTip(_translate("MainWindow", "Serial Port", None))
        self.OpenButton.setToolTip(_translate("MainWindow", "Open Communication", None))
        self.OpenButton.setStatusTip(_translate("MainWindow", "Open Communication", None))
        self.OpenButton.setText(_translate("MainWindow", "Open", None))
        self.CloseButton.setToolTip(_translate("MainWindow", "Close Communication", None))
        self.CloseButton.setStatusTip(_translate("MainWindow", "Close Communication", None))
        self.CloseButton.setText(_translate("MainWindow", "Close", None))
        self.label_7.setText(_translate("MainWindow", "Com. Port:", None))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Acquisition Preferences", None))
        self.label_5.setText(_translate("MainWindow", "Acquisition Interval [s]:", None))
        self.t_aq.setToolTip(_translate("MainWindow", "Acquisition Interval", None))
        self.t_aq.setStatusTip(_translate("MainWindow", "Acquisition Interval", None))
        self.cmp.setToolTip(_translate("MainWindow", "Number of points in graph", None))
        self.cmp.setStatusTip(_translate("MainWindow", "Number of points in graph", None))
        self.label_6.setText(_translate("MainWindow", "Number of Graph Points:", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot Preferences", None))
        self.PlotBox1.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox1.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot1.setToolTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot1.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot1.setText(_translate("MainWindow", "Plot 1:", None))
        self.PlotBox2.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox2.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot2.setToolTip(_translate("MainWindow", "Enable/Disable Plot 2", None))
        self.checkPlot2.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1", None))
        self.checkPlot2.setText(_translate("MainWindow", "Plot 2:", None))
        self.PlotBox3.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox3.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot3.setToolTip(_translate("MainWindow", "Enable/Disable Plot 3", None))
        self.checkPlot3.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 3", None))
        self.checkPlot3.setText(_translate("MainWindow", "Plot 3:", None))
        self.PlotBox4.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox4.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot4.setToolTip(_translate("MainWindow", "Enable/Disable Plot 4", None))
        self.checkPlot4.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 4", None))
        self.checkPlot4.setText(_translate("MainWindow", "Plot 4:", None))
        self.PlotBox5.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox5.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot5.setToolTip(_translate("MainWindow", "Enable/Disable Plot 5", None))
        self.checkPlot5.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 5", None))
        self.checkPlot5.setText(_translate("MainWindow", "Plot 5:", None))
        self.PlotBox6.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox6.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot6.setToolTip(_translate("MainWindow", "Enable/Disable Plot 6", None))
        self.checkPlot6.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 6", None))
        self.checkPlot6.setText(_translate("MainWindow", "Plot 6:", None))
        self.PlotBox7.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox7.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot7.setToolTip(_translate("MainWindow", "Enable/Disable Plot 7", None))
        self.checkPlot7.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 7", None))
        self.checkPlot7.setText(_translate("MainWindow", "Plot 7:", None))
        self.PlotBox8.setToolTip(_translate("MainWindow", "Select Plot Curve", None))
        self.PlotBox8.setStatusTip(_translate("MainWindow", "Select Plot Curve", None))
        self.checkPlot8.setToolTip(_translate("MainWindow", "Enable/Disable Plot 8", None))
        self.checkPlot8.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 8", None))
        self.checkPlot8.setText(_translate("MainWindow", "Plot 8:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preferences), _translate("MainWindow", "Preferences", None))

from PlotGUI_Qwt_Multi import SimplePlot
