# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FogaleNEW_v7.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Variables import var

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1150, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Monitor = QtWidgets.QWidget()
        self.Monitor.setObjectName("Monitor")
        self.gridLayout = QtWidgets.QGridLayout(self.Monitor)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_5.setMinimumSize(QtCore.QSize(140, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(140, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame = QtWidgets.QFrame(self.groupBox_5)
        self.frame.setMinimumSize(QtCore.QSize(0, 32))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.led1_y = QtWidgets.QLabel(self.frame)
        self.led1_y.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led1_y.setText("")
        self.led1_y.setPixmap(QtGui.QPixmap("../Images/glossy_yellow_button.ico"))
        self.led1_y.setScaledContents(True)
        self.led1_y.setObjectName("led1_y")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 5, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.led1_r = QtWidgets.QLabel(self.frame)
        self.led1_r.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led1_r.setText("")
        self.led1_r.setPixmap(QtGui.QPixmap("../Images/glossy_red_button.ico"))
        self.led1_r.setScaledContents(True)
        self.led1_r.setObjectName("led1_r")
        self.led1_g = QtWidgets.QLabel(self.frame)
        self.led1_g.setEnabled(True)
        self.led1_g.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led1_g.setText("")
        self.led1_g.setPixmap(QtGui.QPixmap("../Images/glossy_green_button.ico"))
        self.led1_g.setScaledContents(True)
        self.led1_g.setObjectName("led1_g")
        self.verticalLayout_16.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.led2_y = QtWidgets.QLabel(self.frame_2)
        self.led2_y.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led2_y.setText("")
        self.led2_y.setPixmap(QtGui.QPixmap("../Images/glossy_yellow_button.ico"))
        self.led2_y.setScaledContents(True)
        self.led2_y.setObjectName("led2_y")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 5, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.led2_r = QtWidgets.QLabel(self.frame_2)
        self.led2_r.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led2_r.setText("")
        self.led2_r.setPixmap(QtGui.QPixmap("../Images/glossy_red_button.ico"))
        self.led2_r.setScaledContents(True)
        self.led2_r.setObjectName("led2_r")
        self.led2_g = QtWidgets.QLabel(self.frame_2)
        self.led2_g.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led2_g.setText("")
        self.led2_g.setPixmap(QtGui.QPixmap("../Images/glossy_green_button.ico"))
        self.led2_g.setScaledContents(True)
        self.led2_g.setObjectName("led2_g")
        self.verticalLayout_16.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.led3_y = QtWidgets.QLabel(self.frame_3)
        self.led3_y.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led3_y.setText("")
        self.led3_y.setPixmap(QtGui.QPixmap("../Images/glossy_yellow_button.ico"))
        self.led3_y.setScaledContents(True)
        self.led3_y.setObjectName("led3_y")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(40, 5, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.led3_r = QtWidgets.QLabel(self.frame_3)
        self.led3_r.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led3_r.setText("")
        self.led3_r.setPixmap(QtGui.QPixmap("../Images/glossy_red_button.ico"))
        self.led3_r.setScaledContents(True)
        self.led3_r.setObjectName("led3_r")
        self.led3_g = QtWidgets.QLabel(self.frame_3)
        self.led3_g.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led3_g.setText("")
        self.led3_g.setPixmap(QtGui.QPixmap("../Images/glossy_green_button.ico"))
        self.led3_g.setScaledContents(True)
        self.led3_g.setObjectName("led3_g")
        self.verticalLayout_16.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.led4_y = QtWidgets.QLabel(self.frame_4)
        self.led4_y.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led4_y.setText("")
        self.led4_y.setPixmap(QtGui.QPixmap("../Images/glossy_yellow_button.ico"))
        self.led4_y.setScaledContents(True)
        self.led4_y.setObjectName("led4_y")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(40, 5, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStatusTip("")
        self.label_4.setObjectName("label_4")
        self.led4_g = QtWidgets.QLabel(self.frame_4)
        self.led4_g.setEnabled(True)
        self.led4_g.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led4_g.setText("")
        self.led4_g.setPixmap(QtGui.QPixmap("../Images/glossy_green_button.ico"))
        self.led4_g.setScaledContents(True)
        self.led4_g.setObjectName("led4_g")
        self.led4_r = QtWidgets.QLabel(self.frame_4)
        self.led4_r.setGeometry(QtCore.QRect(0, 0, 35, 35))
        self.led4_r.setText("")
        self.led4_r.setPixmap(QtGui.QPixmap("../Images/glossy_red_button.ico"))
        self.led4_r.setScaledContents(True)
        self.led4_r.setObjectName("led4_r")
        self.verticalLayout_16.addWidget(self.frame_4)
        self.ResButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ResButton.setObjectName("ResButton")
        self.verticalLayout_16.addWidget(self.ResButton)
        self.RefButton = QtWidgets.QPushButton(self.groupBox_5)
        self.RefButton.setObjectName("RefButton")
        self.verticalLayout_16.addWidget(self.RefButton)
        self.gridLayout.addWidget(self.groupBox_5, 1, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_4.setMinimumSize(QtCore.QSize(240, 160))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 260))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(30)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Monitor)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = SimplePlot(self.groupBox_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_6.addWidget(self.widget)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 3)
        self.tabWidget.addTab(self.Monitor, "")
        self.Preferences = QtWidgets.QWidget()
        self.Preferences.setObjectName("Preferences")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Preferences)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Preferences)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame1 = QtWidgets.QFrame(self.groupBox_7)
        self.frame1.setMinimumSize(QtCore.QSize(0, 80))
        self.frame1.setObjectName("frame1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkPlot1 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot1.setChecked(False)
        self.checkPlot1.setObjectName("checkPlot1")
        self.gridLayout_2.addWidget(self.checkPlot1, 0, 0, 1, 1)
        self.checkPlot2 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot2.setObjectName("checkPlot2")
        self.gridLayout_2.addWidget(self.checkPlot2, 0, 1, 1, 1)
        self.checkPlot3 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot3.setObjectName("checkPlot3")
        self.gridLayout_2.addWidget(self.checkPlot3, 0, 2, 1, 1)
        self.checkPlot4 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot4.setObjectName("checkPlot4")
        self.gridLayout_2.addWidget(self.checkPlot4, 0, 3, 1, 1)
        self.checkPlot5 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot5.setObjectName("checkPlot5")
        self.gridLayout_2.addWidget(self.checkPlot5, 0, 4, 1, 1)
        self.checkPlot6 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot6.setObjectName("checkPlot6")
        self.gridLayout_2.addWidget(self.checkPlot6, 0, 5, 1, 1)
        self.checkPlot7 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot7.setObjectName("checkPlot7")
        self.gridLayout_2.addWidget(self.checkPlot7, 0, 6, 1, 1)
        self.checkPlot8 = QtWidgets.QCheckBox(self.frame1)
        self.checkPlot8.setObjectName("checkPlot8")
        self.gridLayout_2.addWidget(self.checkPlot8, 0, 7, 1, 1)
        self.PlotBox1 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox1.setObjectName("PlotBox1")
        self.gridLayout_2.addWidget(self.PlotBox1, 1, 0, 1, 1)
        self.PlotBox2 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox2.setObjectName("PlotBox2")
        self.gridLayout_2.addWidget(self.PlotBox2, 1, 1, 1, 1)
        self.PlotBox3 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox3.setObjectName("PlotBox3")
        self.gridLayout_2.addWidget(self.PlotBox3, 1, 2, 1, 1)
        self.PlotBox4 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox4.setObjectName("PlotBox4")
        self.gridLayout_2.addWidget(self.PlotBox4, 1, 3, 1, 1)
        self.PlotBox5 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox5.setObjectName("PlotBox5")
        self.gridLayout_2.addWidget(self.PlotBox5, 1, 4, 1, 1)
        self.PlotBox6 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox6.setObjectName("PlotBox6")
        self.gridLayout_2.addWidget(self.PlotBox6, 1, 5, 1, 1)
        self.PlotBox7 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox7.setObjectName("PlotBox7")
        self.gridLayout_2.addWidget(self.PlotBox7, 1, 6, 1, 1)
        self.PlotBox8 = QtWidgets.QComboBox(self.frame1)
        self.PlotBox8.setObjectName("PlotBox8")
        self.gridLayout_2.addWidget(self.PlotBox8, 1, 7, 1, 1)
        self.horizontalLayout.addWidget(self.frame1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Preferences)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(250, 110))
        self.groupBox_8.setMaximumSize(QtCore.QSize(220, 120))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(20, 32, 141, 16))
        self.label_5.setObjectName("label_5")
        self.t_aq = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.t_aq.setGeometry(QtCore.QRect(170, 30, 62, 22))
        self.t_aq.setSingleStep(0.01)
        self.t_aq.setProperty("value", 10.0)
        self.t_aq.setObjectName("t_aq")
        self.cmp = QtWidgets.QSpinBox(self.groupBox_8)
        self.cmp.setGeometry(QtCore.QRect(170, 64, 56, 22))
        self.cmp.setMinimum(2)
        self.cmp.setMaximum(10000)
        self.cmp.setProperty("value", 100)
        self.cmp.setObjectName("cmp")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(13, 66, 141, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(100, 120))
        self.groupBox_6.setObjectName("groupBox_6")
        self.check3 = QtWidgets.QCheckBox(self.groupBox_6)
        self.check3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.check3.setWhatsThis("")
        self.check3.setChecked(True)
        self.check3.setObjectName("check3")
        self.check4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.check4.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.check4.setChecked(True)
        self.check4.setObjectName("check4")
        self.check1 = QtWidgets.QCheckBox(self.groupBox_6)
        self.check1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.check1.setChecked(True)
        self.check1.setObjectName("check1")
        self.check2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.check2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.check2.setChecked(True)
        self.check2.setObjectName("check2")
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(self.frame2)
        self.groupBox.setMaximumSize(QtCore.QSize(220, 120))
        self.groupBox.setObjectName("groupBox")
        self.PortBox = QtWidgets.QComboBox(self.groupBox)
        self.PortBox.setGeometry(QtCore.QRect(20, 45, 69, 22))
        self.PortBox.setObjectName("PortBox")
        self.OpenButton = QtWidgets.QPushButton(self.groupBox)
        self.OpenButton.setGeometry(QtCore.QRect(120, 15, 75, 23))
        self.OpenButton.setObjectName("OpenButton")
        self.CloseButton = QtWidgets.QPushButton(self.groupBox)
        self.CloseButton.setGeometry(QtCore.QRect(120, 45, 75, 23))
        self.CloseButton.setObjectName("CloseButton")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 25, 61, 16))
        self.label_7.setObjectName("label_7")
        self.RefreshButton = QtWidgets.QPushButton(self.groupBox)
        self.RefreshButton.setGeometry(QtCore.QRect(120, 75, 75, 23))
        self.RefreshButton.setObjectName("RefreshButton")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_5.addWidget(self.frame2)
        self.frame3 = QtWidgets.QFrame(self.groupBox_2)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame3)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(30)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(29, item)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.label_9 = QtWidgets.QLabel(self.frame3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame3)
        self.tableWidget_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(32)
        self.tableWidget_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(31, item)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.verticalLayout_5.addWidget(self.frame3)
        self.frame4 = QtWidgets.QFrame(self.groupBox_2)
        self.frame4.setObjectName("frame4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LoadButton = QtWidgets.QPushButton(self.frame4)
        self.LoadButton.setMinimumSize(QtCore.QSize(150, 0))
        self.LoadButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LoadButton.setObjectName("LoadButton")
        self.horizontalLayout_3.addWidget(self.LoadButton)
        self.SaveButton = QtWidgets.QPushButton(self.frame4)
        self.SaveButton.setMinimumSize(QtCore.QSize(150, 0))
        self.SaveButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout_3.addWidget(self.SaveButton)
        self.verticalLayout_5.addWidget(self.frame4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.Preferences, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cal = QtWidgets.QCalendarWidget(self.tab)
        self.cal.setMinimumSize(QtCore.QSize(0, 50))
        self.cal.setGridVisible(True)
        self.cal.setObjectName("cal")
        self.gridLayout_3.addWidget(self.cal, 0, 0, 2, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_play = QtWidgets.QPushButton(self.groupBox_12)
        self.btn_play.setObjectName("btn_play")
        self.verticalLayout_9.addWidget(self.btn_play)
        self.gridLayout_4.addWidget(self.groupBox_12, 3, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plotBox_off = QtWidgets.QComboBox(self.groupBox_11)
        self.plotBox_off.setObjectName("plotBox_off")
        self.plotBox_off.addItem("")
        self.plotBox_off.addItem("")
        self.verticalLayout_7.addWidget(self.plotBox_off)
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.plotBoxSens_off = QtWidgets.QComboBox(self.groupBox_11)
        self.plotBoxSens_off.setObjectName("plotBoxSens_off")
        self.verticalLayout_7.addWidget(self.plotBoxSens_off)
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.logDateTime_off = QtWidgets.QLineEdit(self.groupBox_11)
        self.logDateTime_off.setObjectName("logDateTime_off")
        self.verticalLayout_7.addWidget(self.logDateTime_off)
        self.setRefBtn_off = QtWidgets.QPushButton(self.groupBox_11)
        self.setRefBtn_off.setObjectName("setRefBtn_off")
        self.verticalLayout_7.addWidget(self.setRefBtn_off)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.plotBoxShift_off = QtWidgets.QSpinBox(self.groupBox_11)
        self.plotBoxShift_off.setObjectName("plotBoxShift_off")
        self.verticalLayout_7.addWidget(self.plotBoxShift_off)
        self.checkShift_off = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkShift_off.setObjectName("checkShift_off")
        self.verticalLayout_7.addWidget(self.checkShift_off)
        self.gridLayout_4.addWidget(self.groupBox_11, 0, 1, 4, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plotAbsBtn_off = QtWidgets.QPushButton(self.groupBox_10)
        self.plotAbsBtn_off.setObjectName("plotAbsBtn_off")
        self.verticalLayout_8.addWidget(self.plotAbsBtn_off)
        self.plotRefFixaBtn_off = QtWidgets.QPushButton(self.groupBox_10)
        self.plotRefFixaBtn_off.setObjectName("plotRefFixaBtn_off")
        self.verticalLayout_8.addWidget(self.plotRefFixaBtn_off)
        self.plotRefMedGBtn_off = QtWidgets.QPushButton(self.groupBox_10)
        self.plotRefMedGBtn_off.setObjectName("plotRefMedGBtn_off")
        self.verticalLayout_8.addWidget(self.plotRefMedGBtn_off)
        self.plotRefSensorBtn_off = QtWidgets.QPushButton(self.groupBox_10)
        self.plotRefSensorBtn_off.setObjectName("plotRefSensorBtn_off")
        self.verticalLayout_8.addWidget(self.plotRefSensorBtn_off)
        self.gridLayout_4.addWidget(self.groupBox_10, 0, 0, 3, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.logOutput_off = QtWidgets.QTextEdit(self.tab)
        self.logOutput_off.setMaximumSize(QtCore.QSize(350, 16777215))
        self.logOutput_off.setObjectName("logOutput_off")
        self.gridLayout_3.addWidget(self.logOutput_off, 1, 1, 2, 1)
        self.frame5 = QtWidgets.QFrame(self.tab)
        self.frame5.setMinimumSize(QtCore.QSize(0, 45))
        self.frame5.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame5.setObjectName("frame5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame5)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 1)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn1 = QtWidgets.QPushButton(self.frame5)
        self.btn1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_4.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.frame5)
        self.btn2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_4.addWidget(self.btn2)
        self.gridLayout_3.addWidget(self.frame5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_on = SimplePlot_on(self.groupBox_13)
        self.widget_on.setObjectName("widget_on")
        self.verticalLayout_15.addWidget(self.widget_on)
        self.verticalLayout_14.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(1100, 200))
        self.groupBox_14.setMaximumSize(QtCore.QSize(99999, 200))
        self.groupBox_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_14.setFlat(False)
        self.groupBox_14.setCheckable(False)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setMinimumSize(QtCore.QSize(110, 150))
        self.groupBox_15.setMaximumSize(QtCore.QSize(110, 150))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_ref1 = QtWidgets.QLabel(self.groupBox_15)
        self.label_ref1.setGeometry(QtCore.QRect(7, 22, 91, 16))
        self.label_ref1.setObjectName("label_ref1")
        self.refBox_on = QtWidgets.QComboBox(self.groupBox_15)
        self.refBox_on.setGeometry(QtCore.QRect(7, 43, 100, 22))
        self.refBox_on.setObjectName("refBox_on")
        self.refBox_on.addItem("")
        self.refBox_on.addItem("")
        self.refBox_on.addItem("")
        self.refBox_on.addItem("")
        self.refBox_on.addItem("")
        self.plotBoxSens_on = QtWidgets.QComboBox(self.groupBox_15)
        self.plotBoxSens_on.setGeometry(QtCore.QRect(7, 95, 81, 16))
        self.plotBoxSens_on.setObjectName("plotBoxSens_on")
        self.setRef_onBtn = QtWidgets.QPushButton(self.groupBox_15)
        self.setRef_onBtn.setGeometry(QtCore.QRect(7, 123, 90, 21))
        self.setRef_onBtn.setObjectName("setRef_onBtn")
        self.label_20 = QtWidgets.QLabel(self.groupBox_15)
        self.label_20.setGeometry(QtCore.QRect(7, 75, 91, 16))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.groupBox_15)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_16.setMinimumSize(QtCore.QSize(150, 150))
        self.groupBox_16.setMaximumSize(QtCore.QSize(150, 150))
        self.groupBox_16.setObjectName("groupBox_16")
        self.cmp_on = QtWidgets.QSpinBox(self.groupBox_16)
        self.cmp_on.setGeometry(QtCore.QRect(92, 23, 51, 22))
        self.cmp_on.setWrapping(True)
        self.cmp_on.setAccelerated(False)
        self.cmp_on.setProperty("showGroupSeparator", True)
        self.cmp_on.setMaximum(1000)
        self.cmp_on.setObjectName("cmp_on")
        self.label_14 = QtWidgets.QLabel(self.groupBox_16)
        self.label_14.setGeometry(QtCore.QRect(8, 18, 81, 31))
        self.label_14.setObjectName("label_14")
        self.checkCmp_on = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkCmp_on.setGeometry(QtCore.QRect(10, 44, 125, 20))
        self.checkCmp_on.setObjectName("checkCmp_on")
        
        self.checkPlot_level_on = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkPlot_level_on.setGeometry(QtCore.QRect(10, 44, 111, 60))
        self.checkPlot_level_on.setObjectName("checkPlot_level_on")
        self.checkPlot_level_on.setChecked(1) # default: level plot activated
        
        self.checkPlot_temp_on = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkPlot_temp_on.setGeometry(QtCore.QRect(10, 44, 130, 100))
        self.checkPlot_temp_on.setObjectName("checkPlot_temp_on")
        self.checkPlot_temp_on.setChecked(0)
        
        #self.plotBox_on = QtWidgets.QComboBox(self.groupBox_16)
        #self.plotBox_on.setGeometry(QtCore.QRect(20, 70, 81, 16))
        #self.plotBox_on.setObjectName("plotBox_on")
        #self.plotBox_on.addItem("")
        #self.plotBox_on.addItem("")
        self.startPlotBtn_on = QtWidgets.QPushButton(self.groupBox_16)
        self.startPlotBtn_on.setGeometry(QtCore.QRect(20, 104, 50, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPlotBtn_on.sizePolicy().hasHeightForWidth())
        self.startPlotBtn_on.setSizePolicy(sizePolicy)
        self.startPlotBtn_on.setObjectName("startPlotBtn_on")
        self.stopPlotBtn_on = QtWidgets.QPushButton(self.groupBox_16)
        self.stopPlotBtn_on.setGeometry(QtCore.QRect(80, 104, 50, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopPlotBtn_on.sizePolicy().hasHeightForWidth())
        self.stopPlotBtn_on.setSizePolicy(sizePolicy)
        self.stopPlotBtn_on.setObjectName("stopPlotBtn_on")
        self.horizontalLayout_5.addWidget(self.groupBox_16)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_17.setMinimumSize(QtCore.QSize(190, 150))
        self.groupBox_17.setMaximumSize(QtCore.QSize(190, 150))
        self.groupBox_17.setObjectName("groupBox_17")
        self.logMinY = QtWidgets.QLineEdit(self.groupBox_17)
        self.logMinY.setGeometry(QtCore.QRect(67, 37, 51, 16))
        self.logMinY.setObjectName("logMinY")
        self.logMaxY = QtWidgets.QLineEdit(self.groupBox_17)
        self.logMaxY.setGeometry(QtCore.QRect(67, 62, 51, 16))
        self.logMaxY.setObjectName("logMaxY")
        self.logMinX = QtWidgets.QLineEdit(self.groupBox_17)
        self.logMinX.setGeometry(QtCore.QRect(129, 37, 51, 16))
        self.logMinX.setObjectName("logMinX")
        self.logMaxX = QtWidgets.QLineEdit(self.groupBox_17)
        self.logMaxX.setGeometry(QtCore.QRect(129, 62, 51, 16))
        self.logMaxX.setObjectName("logMaxX")
        self.label_17 = QtWidgets.QLabel(self.groupBox_17)
        self.label_17.setGeometry(QtCore.QRect(72, 19, 55, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_17)
        self.label_18.setGeometry(QtCore.QRect(138, 19, 55, 16))
        self.label_18.setObjectName("label_18")
        self.setAutoScaleBtn = QtWidgets.QPushButton(self.groupBox_17)
        self.setAutoScaleBtn.setGeometry(QtCore.QRect(8, 110, 81, 21))
        self.setAutoScaleBtn.setObjectName("setAutoScaleBtn")
        self.label_16 = QtWidgets.QLabel(self.groupBox_17)
        self.label_16.setGeometry(QtCore.QRect(9, 34, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_17)
        self.label_15.setGeometry(QtCore.QRect(9, 59, 55, 16))
        self.label_15.setObjectName("label_15")
        self.plotBox_data = QtWidgets.QComboBox(self.groupBox_17)
        self.plotBox_data.setGeometry(QtCore.QRect(59, 84, 81, 16))
        self.plotBox_data.setObjectName("plotBox_data")
        self.label_21 = QtWidgets.QLabel(self.groupBox_17)
        self.label_21.setGeometry(QtCore.QRect(28, 82, 55, 16))
        self.label_21.setObjectName("label_21")
        self.setScaleBtn = QtWidgets.QPushButton(self.groupBox_17)
        self.setScaleBtn.setGeometry(QtCore.QRect(100, 110, 81, 21))
        self.setScaleBtn.setObjectName("setScaleBtn")
        self.horizontalLayout_5.addWidget(self.groupBox_17)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_19.setMinimumSize(QtCore.QSize(335, 160))
        self.groupBox_19.setMaximumSize(QtCore.QSize(335, 160))
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, 11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.groupBox_19)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.checkPlot1_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot1_on.setObjectName("checkPlot1_on")
        self.verticalLayout_10.addWidget(self.checkPlot1_on)
        self.checkPlot2_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot2_on.setObjectName("checkPlot2_on")
        self.verticalLayout_10.addWidget(self.checkPlot2_on)
        self.checkPlot3_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot3_on.setObjectName("checkPlot3_on")
        self.verticalLayout_10.addWidget(self.checkPlot3_on)
        self.checkPlot4_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot4_on.setObjectName("checkPlot4_on")
        self.verticalLayout_10.addWidget(self.checkPlot4_on)
        self.checkPlot5_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot5_on.setObjectName("checkPlot5_on")
        self.verticalLayout_10.addWidget(self.checkPlot5_on)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox_19)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_11.addWidget(self.label_22)
        self.checkPlot6_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot6_on.setObjectName("checkPlot6_on")
        self.verticalLayout_11.addWidget(self.checkPlot6_on)
        self.checkPlot7_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot7_on.setObjectName("checkPlot7_on")
        self.verticalLayout_11.addWidget(self.checkPlot7_on)
        self.checkPlot8_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot8_on.setObjectName("checkPlot8_on")
        self.verticalLayout_11.addWidget(self.checkPlot8_on)
        self.checkPlot9_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot9_on.setObjectName("checkPlot9_on")
        self.verticalLayout_11.addWidget(self.checkPlot9_on)
        self.checkPlot10_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot10_on.setObjectName("checkPlot10_on")
        self.verticalLayout_11.addWidget(self.checkPlot10_on)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.groupBox_19)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_12.addWidget(self.label_24)
        self.checkPlot11_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot11_on.setObjectName("checkPlot11_on")
        self.verticalLayout_12.addWidget(self.checkPlot11_on)
        self.checkPlot12_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot12_on.setObjectName("checkPlot12_on")
        self.verticalLayout_12.addWidget(self.checkPlot12_on)
        self.checkPlot13_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot13_on.setObjectName("checkPlot13_on")
        self.verticalLayout_12.addWidget(self.checkPlot13_on)
        self.checkPlot14_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot14_on.setObjectName("checkPlot14_on")
        self.verticalLayout_12.addWidget(self.checkPlot14_on)
        self.checkPlot15_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot15_on.setObjectName("checkPlot15_on")
        self.verticalLayout_12.addWidget(self.checkPlot15_on)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.groupBox_19)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_13.addWidget(self.label_25)
        self.checkPlot16_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot16_on.setObjectName("checkPlot16_on")
        self.verticalLayout_13.addWidget(self.checkPlot16_on)
        self.checkPlot17_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot17_on.setObjectName("checkPlot17_on")
        self.verticalLayout_13.addWidget(self.checkPlot17_on)
        self.checkPlot18_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot18_on.setObjectName("checkPlot18_on")
        self.verticalLayout_13.addWidget(self.checkPlot18_on)
        self.checkPlot19_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot19_on.setObjectName("checkPlot19_on")
        self.verticalLayout_13.addWidget(self.checkPlot19_on)
        self.checkPlot20_on = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkPlot20_on.setObjectName("checkPlot20_on")
        self.verticalLayout_13.addWidget(self.checkPlot20_on)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.horizontalLayout_5.addWidget(self.groupBox_19)
        self.logOutput_on = QtWidgets.QTextEdit(self.groupBox_14)
        self.logOutput_on.setMinimumSize(QtCore.QSize(120, 160))
        self.logOutput_on.setMaximumSize(QtCore.QSize(9999, 160))
        self.logOutput_on.setObjectName("logOutput_on")
        self.horizontalLayout_5.addWidget(self.logOutput_on)
        self.verticalLayout_14.addWidget(self.groupBox_14)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.groupBox_5.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Rack\'s State"))
        self.led1_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led1_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.label.setText(_translate("MainWindow", "Rack 1"))
        self.led1_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led1_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led1_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led1_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led2_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led2_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.label_2.setText(_translate("MainWindow", "Rack 2"))
        self.led2_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led2_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led2_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led2_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led3_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led3_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.label_3.setText(_translate("MainWindow", "Rack 3"))
        self.led3_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led3_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led3_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led3_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led4_y.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led4_y.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.label_4.setText(_translate("MainWindow", "Rack 4"))
        self.led4_g.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led4_g.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led4_r.setToolTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.led4_r.setStatusTip(_translate("MainWindow", "If red: Rack not selected; If yellow: Rack is turned off or has issue; If green: Rack ok."))
        self.ResButton.setToolTip(_translate("MainWindow", "Reset Racks"))
        self.ResButton.setStatusTip(_translate("MainWindow", "Reset Racks"))
        self.ResButton.setText(_translate("MainWindow", "Reset"))
        self.RefButton.setToolTip(_translate("MainWindow", "Set Current Values as Reference"))
        self.RefButton.setStatusTip(_translate("MainWindow", "Set Current Values as Reference"))
        self.RefButton.setText(_translate("MainWindow", "Set Ref"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "D [mm]"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "D-Do [mm]"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Davg [mm]"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "T [ºC]"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "T-To [ºC]"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tavg [ºC]"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-32"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-33"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-34"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-35"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-36"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-37"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-38"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-39"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-40"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-41"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-43"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-44"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-45"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-46"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-47"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-52"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-54"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-55"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-56"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-57"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-59"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Graphics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Monitor), _translate("MainWindow", "Monitor"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot Preferences"))
        self.checkPlot1.setToolTip(_translate("MainWindow", "Enable/Disable Plot 1"))
        self.checkPlot1.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1"))
        self.checkPlot1.setText(_translate("MainWindow", "Plot 1:"))
        self.checkPlot2.setToolTip(_translate("MainWindow", "Enable/Disable Plot 2"))
        self.checkPlot2.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 1"))
        self.checkPlot2.setText(_translate("MainWindow", "Plot 2:"))
        self.checkPlot3.setToolTip(_translate("MainWindow", "Enable/Disable Plot 3"))
        self.checkPlot3.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 3"))
        self.checkPlot3.setText(_translate("MainWindow", "Plot 3:"))
        self.checkPlot4.setToolTip(_translate("MainWindow", "Enable/Disable Plot 4"))
        self.checkPlot4.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 4"))
        self.checkPlot4.setText(_translate("MainWindow", "Plot 4:"))
        self.checkPlot5.setToolTip(_translate("MainWindow", "Enable/Disable Plot 5"))
        self.checkPlot5.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 5"))
        self.checkPlot5.setText(_translate("MainWindow", "Plot 5:"))
        self.checkPlot6.setToolTip(_translate("MainWindow", "Enable/Disable Plot 6"))
        self.checkPlot6.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 6"))
        self.checkPlot6.setText(_translate("MainWindow", "Plot 6:"))
        self.checkPlot7.setToolTip(_translate("MainWindow", "Enable/Disable Plot 7"))
        self.checkPlot7.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 7"))
        self.checkPlot7.setText(_translate("MainWindow", "Plot 7:"))
        self.checkPlot8.setToolTip(_translate("MainWindow", "Enable/Disable Plot 8"))
        self.checkPlot8.setStatusTip(_translate("MainWindow", "Enable/Disable Plot 8"))
        self.checkPlot8.setText(_translate("MainWindow", "Plot 8:"))
        self.PlotBox1.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox1.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox2.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox2.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox3.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox3.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox4.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox4.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox5.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox5.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox6.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox6.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox7.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox7.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox8.setToolTip(_translate("MainWindow", "Select Plot Curve"))
        self.PlotBox8.setStatusTip(_translate("MainWindow", "Select Plot Curve"))
        self.groupBox_2.setTitle(_translate("MainWindow", "General Preferences"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Acquisition Preferences"))
        self.label_5.setText(_translate("MainWindow", "Acquisition Interval [s]:"))
        self.t_aq.setToolTip(_translate("MainWindow", "Acquisition Interval"))
        self.t_aq.setStatusTip(_translate("MainWindow", "Acquisition Interval"))
        self.cmp.setToolTip(_translate("MainWindow", "Number of points in graph"))
        self.cmp.setStatusTip(_translate("MainWindow", "Number of points in graph"))
        self.label_6.setText(_translate("MainWindow", "Number of Graph Points:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Enable Racks"))
        self.check3.setToolTip(_translate("MainWindow", "Enable/Disable Rack 3"))
        self.check3.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 3"))
        self.check3.setText(_translate("MainWindow", "Rack 3"))
        self.check4.setToolTip(_translate("MainWindow", "Enable/Disable Rack 4"))
        self.check4.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 4"))
        self.check4.setText(_translate("MainWindow", "Rack 4"))
        self.check1.setToolTip(_translate("MainWindow", "Enable/Disable Rack 1"))
        self.check1.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 1"))
        self.check1.setText(_translate("MainWindow", "Rack 1"))
        self.check2.setToolTip(_translate("MainWindow", "Enable/Disable Rack 2"))
        self.check2.setStatusTip(_translate("MainWindow", "Enable/Disable Rack 2"))
        self.check2.setText(_translate("MainWindow", "Rack 2"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Communication"))
        self.PortBox.setToolTip(_translate("MainWindow", "Serial Port"))
        self.PortBox.setStatusTip(_translate("MainWindow", "Serial Port"))
        self.OpenButton.setToolTip(_translate("MainWindow", "Open Communication"))
        self.OpenButton.setStatusTip(_translate("MainWindow", "Open Communication"))
        self.OpenButton.setText(_translate("MainWindow", "Open"))
        self.CloseButton.setToolTip(_translate("MainWindow", "Close Communication"))
        self.CloseButton.setStatusTip(_translate("MainWindow", "Close Communication"))
        self.CloseButton.setText(_translate("MainWindow", "Close"))
        self.label_7.setText(_translate("MainWindow", "Com. Port:"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.label_8.setText(_translate("MainWindow", "Reference Values:"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Do [mm]"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "To [ºC]"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-32"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-33"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-34"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-35"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-36"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-37"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-38"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-39"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-40"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-41"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-43"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-44"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-45"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-46"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-47"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50"))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51"))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-52"))
        item = self.tableWidget_2.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53"))
        item = self.tableWidget_2.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-54"))
        item = self.tableWidget_2.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-55"))
        item = self.tableWidget_2.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-56"))
        item = self.tableWidget_2.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-57"))
        item = self.tableWidget_2.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58"))
        item = self.tableWidget_2.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-59"))
        item = self.tableWidget_2.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60"))
        item = self.tableWidget_2.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61"))
        self.label_9.setText(_translate("MainWindow", "Average Values:"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Davg [mm]"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tavg [ºC]"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "H7DC-32"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H7DC-33"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H7DC-34"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "H7DC-35"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "H7DC-36"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H7DC-37"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "H7DC-38"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H7DC-39"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "H7DC-40"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "H7DC-41"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "H7DC-42"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "H7DC-43"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "H7DC-44"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "H7DC-45"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "H7DC-46"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "H7DC-47"))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "H7DC-48"))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "H7DC-49"))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "H7DC-50"))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "H7DC-51"))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "H7DC-52"))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "H7DC-53"))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "H7DC-54"))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "H7DC-55"))
        item = self.tableWidget_3.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "H7DC-56"))
        item = self.tableWidget_3.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "H7DC-57"))
        item = self.tableWidget_3.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "H7DC-58"))
        item = self.tableWidget_3.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "H7DC-59"))
        item = self.tableWidget_3.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "H7DC-60"))
        item = self.tableWidget_3.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "H7DC-61"))
        item = self.tableWidget_3.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "H7DC-62"))
        item = self.tableWidget_3.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "H7DC-63"))
        self.LoadButton.setToolTip(_translate("MainWindow", "Load Preferences From File"))
        self.LoadButton.setStatusTip(_translate("MainWindow", "Load Preferences From File"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.SaveButton.setToolTip(_translate("MainWindow", "Save Preferences"))
        self.SaveButton.setStatusTip(_translate("MainWindow", "Save Preferences"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preferences), _translate("MainWindow", "Preferences"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Plot definitions"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Plot actions"))
        self.btn_play.setText(_translate("MainWindow", "Plot"))
        self.groupBox_11.setTitle(_translate("MainWindow", "General preferences"))
        self.plotBox_off.setItemText(0, _translate("MainWindow", "Level"))
        self.plotBox_off.setItemText(1, _translate("MainWindow", "Temperature"))
        self.label_10.setText(_translate("MainWindow", "Referenced sensor"))
        self.label_12.setToolTip(_translate("MainWindow", "Set date and time of the data that is wanted to be referenced. Format: HH:MM:SS dd/mm/yyyy"))
        self.label_12.setStatusTip(_translate("MainWindow", "Set date and time of the data that is wanted to be referenced. Format: HH:MM:SS dd/mm/yyyy"))
        self.label_12.setText(_translate("MainWindow", "Datetime reference (for Time fixed plot)"))
        self.logDateTime_off.setToolTip(_translate("MainWindow", "Set date and time of the data that is wanted to be referenced. Format: HH:MM:SS dd/mm/yyyy"))
        self.logDateTime_off.setStatusTip(_translate("MainWindow", "Set date and time of the data that is wanted to be referenced. Format: HH:MM:SS dd/mm/yyyy"))
        self.setRefBtn_off.setText(_translate("MainWindow", "Set datetime reference"))
        self.label_13.setText(_translate("MainWindow", "Sampling shift [seg]"))
        self.checkShift_off.setText(_translate("MainWindow", "Set sampling shift"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Reference definitions"))
        self.plotAbsBtn_off.setText(_translate("MainWindow", "Absolut values"))
        self.plotRefFixaBtn_off.setText(_translate("MainWindow", "Time fixed"))
        self.plotRefMedGBtn_off.setText(_translate("MainWindow", "Overall Mean"))
        self.plotRefSensorBtn_off.setText(_translate("MainWindow", "Specific Sensor"))
        self.btn1.setText(_translate("MainWindow", "Set initial date"))
        self.btn2.setText(_translate("MainWindow", "Set final date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Offline Plot"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Plot"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Plot definitions"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Reference def."))
        self.refBox_on.setItemText(0, _translate("MainWindow", "Raw Values"))
        self.refBox_on.setItemText(1, _translate("MainWindow", "Time Fixed"))
        self.refBox_on.setItemText(2, _translate("MainWindow", "Specific Sensor"))
        self.refBox_on.setItemText(3, _translate("MainWindow", "Overall Mean"))
        self.refBox_on.setItemText(4, _translate("MainWindow", "Local Mean"))
        self.setRef_onBtn.setText(_translate("MainWindow", "Set time ref."))
        self.label_20.setText(_translate("MainWindow", "Sensor ref.:"))
        self.label_ref1.setText(_translate("MainWindow", "Type of ref.:"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Plot options"))
        self.label_14.setText(_translate("MainWindow", "Graph points"))
        self.checkCmp_on.setText(_translate("MainWindow", "Limit Graph points"))
        self.checkPlot_level_on.setText(_translate("MainWindow", "Plot Level"))
        self.checkPlot_temp_on.setText(_translate("MainWindow", "Plot Temperature"))
        
        #self.plotBox_on.setItemText(0, _translate("MainWindow", "Level"))
        #self.plotBox_on.setItemText(1, _translate("MainWindow", "Temperature"))
        self.startPlotBtn_on.setText(_translate("MainWindow", "Start\n"
"Plot"))
        self.stopPlotBtn_on.setText(_translate("MainWindow", "Stop\n"
"Plot"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Scale options"))
        self.label_17.setText(_translate("MainWindow", "Y Axis"))
        self.label_18.setText(_translate("MainWindow", "X Axis"))
        self.setAutoScaleBtn.setText(_translate("MainWindow", "Autoscale"))
        self.label_16.setText(_translate("MainWindow", "Minimum"))
        self.label_15.setText(_translate("MainWindow", "Maximum"))
        self.label_21.setText(_translate("MainWindow", "Date"))
        self.setScaleBtn.setText(_translate("MainWindow", "Set scale"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Plot selection"))
        self.label_19.setText(_translate("MainWindow", "RACK 1"))
        self.checkPlot1_on.setText(_translate("MainWindow", var.disp_sensores[0][0]))
        self.checkPlot2_on.setText(_translate("MainWindow", var.disp_sensores[0][1]))
        self.checkPlot3_on.setText(_translate("MainWindow", var.disp_sensores[0][2]))
        self.checkPlot4_on.setText(_translate("MainWindow", var.disp_sensores[0][3]))
        self.checkPlot5_on.setText(_translate("MainWindow", var.disp_sensores[0][4]))
        self.label_22.setText(_translate("MainWindow", "RACK 2"))
        self.checkPlot6_on.setText(_translate("MainWindow", var.disp_sensores[1][0]))
        self.checkPlot7_on.setText(_translate("MainWindow", var.disp_sensores[1][1]))
        self.checkPlot8_on.setText(_translate("MainWindow", var.disp_sensores[1][2]))
        self.checkPlot9_on.setText(_translate("MainWindow", var.disp_sensores[1][3]))
        self.checkPlot10_on.setText(_translate("MainWindow", var.disp_sensores[1][4]))
        self.label_24.setText(_translate("MainWindow", "RACK 3"))
        self.checkPlot11_on.setText(_translate("MainWindow", var.disp_sensores[2][0]))
        self.checkPlot12_on.setText(_translate("MainWindow", var.disp_sensores[2][1]))
        self.checkPlot13_on.setText(_translate("MainWindow", var.disp_sensores[2][2]))
        self.checkPlot14_on.setText(_translate("MainWindow", var.disp_sensores[2][3]))
        self.checkPlot15_on.setText(_translate("MainWindow", var.disp_sensores[2][4]))
        self.label_25.setText(_translate("MainWindow", "RACK 4"))
        self.checkPlot16_on.setText(_translate("MainWindow", var.disp_sensores[3][0]))
        self.checkPlot17_on.setText(_translate("MainWindow", var.disp_sensores[3][1]))
        self.checkPlot18_on.setText(_translate("MainWindow", var.disp_sensores[3][2]))
        self.checkPlot19_on.setText(_translate("MainWindow", var.disp_sensores[3][3]))
        self.checkPlot20_on.setText(_translate("MainWindow", var.disp_sensores[3][4]))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Online Plot"))

from Plot_definitions import SimplePlot, SimplePlot_on
